const questionsPart2 = [
  "What do you think is the most pressing environmental issue today?",
  "How do you stay informed about current events?",
  "What’s a cultural tradition you find fascinating?",
  "How do you think technology will change our daily lives in 10 years?",
  "What’s an invention you think changed the world the most?",
  "What’s a country whose history you’d like to learn more about?",
  "How do you think climate change affects your community?",
  "What’s your favorite way to explore nature?",
  "How do you think social media impacts society?",
  "What’s a book or documentary that changed your view of the world?",
  "What’s an outdoor activity you want to try?",
  "How do you think urban living affects people’s lifestyles?",
  "What’s a language you’d like to learn, and why?",
  "How do you think globalization has influenced culture?",
  "What’s a food from another country you’d like to try?",
  "What do you know about the history of your hometown?",
  "How do you think art influences society?",
  "What’s a city you find inspiring, and why?",
  "How do you think space exploration benefits humanity?",
  "What’s a scientific discovery that fascinates you?",
  "How do you think education systems could improve?",
  "What’s a famous landmark you want to visit?",
  "How do you think fashion reflects culture?",
  "What’s a festival or celebration you’d like to experience?",
  "How do you think music brings people together?",
  "What’s an environmental habit you practice?",
  "How do you think artificial intelligence will impact jobs?",
  "What’s a movie that shows a culture different from yours?",
  "How do you think travel changes people?",
  "What’s a sport popular in another country that you find interesting?",
  "How do you think cities can become more sustainable?",
  "What’s a traditional craft or skill you admire?",
  "How do you think media shapes public opinion?",
  "What’s a famous person you admire for their social impact?",
  "How do you think the internet has changed communication?",
  "What’s a natural wonder you’d love to see?",
  "How do you think volunteering helps communities?",
  "What’s a historical event you wish you could witness?",
  "How do you think cultural diversity enriches society?",
  "What’s a book set in another country that you enjoyed?",
  "How do you think public transportation could be improved?",
  "What’s a global issue you feel passionate about?",
  "How do you think technology affects privacy?",
  "What’s a traditional dish you’d like to learn to cook?",
  "How do you think wildlife conservation impacts the planet?",
  "What’s a city known for its architecture that you admire?",
  "How do you think education can address social inequality?",
  "What’s a museum or gallery you’d like to visit?",
  "How do you think climate policies affect everyday life?",
  "What’s a language or dialect unique to a region you find interesting?",
  "How do you think renewable energy can change the future?",
  "What’s a cultural practice that surprised you?",
  "How do you think the arts influence mental health?",
  "What’s a country’s cuisine you want to explore more?",
  "How do you think technology influences creativity?",
  "What’s a famous historical figure you’d like to meet?",
  "How do you think urban green spaces benefit people?",
  "What’s a festival that celebrates nature you’d like to attend?",
  "How do you think international cooperation can solve global problems?",
  "What’s a scientific topic you wish was taught more in school?",
  "How do you think fashion trends spread globally?",
  "What’s a natural disaster that has impacted a community you know?",
  "How do you think cultural heritage should be preserved?",
  "What’s a country’s music style that intrigues you?",
  "How do you think technology can help reduce waste?",
  "What’s a traditional form of storytelling you find meaningful?",
  "How do you think urban design affects quality of life?",
  "What’s a local market or bazaar you’d love to visit?",
  "How do you think social movements influence change?",
  "What’s a documentary that opened your eyes to an issue?",
  "How do you think food connects people across cultures?",
  "What’s a wildlife species you find fascinating?",
  "How do you think museums help educate society?",
  "What’s a global challenge you want to learn more about?",
  "How do you think technology changes how we access information?",
  "What’s a tradition you’d like to incorporate into your life?",
  "How do you think climate change affects global migration?",
  "What’s a form of art you’d like to try?",
  "How do you think history lessons can be made more engaging?",
  "What’s a city you think balances tradition and modernity well?",
  "How do you think cultural festivals promote understanding?",
  "What’s a natural environment you want to protect?",
  "How do you think public policy impacts environmental health?",
  "What’s a food-related custom you find interesting?",
  "How do you think technology shapes our identity?",
  "What’s a book about travel or culture that you enjoyed?",
  "How do you think education influences social mobility?",
  "What’s a famous artist or musician you admire?",
  "How do you think urbanization affects wildlife?",
  "What’s a local tradition in your area you find unique?",
  "How do you think volunteering abroad changes perspectives?",
  "What’s a global issue you think deserves more attention?",
  "How do you think digital communication affects relationships?",
  "What’s a natural park or reserve you want to explore?",
  "How do you think technology can improve healthcare?",
  "What’s a cultural symbol that represents your country?",
  "How do you think food waste can be reduced?",
  "What’s a city known for innovation that you admire?",
  "How do you think art can be used to raise awareness?",
  "What’s a scientific breakthrough that excites you?",
  "How do you think urban farming can impact food security?",
  "What’s a cultural stereotype you think should be challenged?",
  "How do you think technology influences education access?",
  "What’s a global festival you’d love to attend?",
  "How do you think natural disasters affect cultural heritage?",
  "What’s a city you think is a great model for sustainability?",
  "How do you think technology impacts language preservation?",
  "What’s a historical site you’d like to explore?",
  "How do you think music festivals foster cultural exchange?",
  "What’s an environmental organization you admire?",
  "How do you think space tourism might change the world?",
  "What’s a traditional dance or performance you find fascinating?",
  "How do you think media representation affects cultural identity?",
  "What’s a global health issue you want to learn more about?",
  "How do you think electric vehicles will change transportation?",
  "What’s a country with a unique political system you find interesting?",
  "How do you think digital art is shaping culture?",
  "What’s a way cities can better support local artists?",
  "How do you think renewable energy adoption can be accelerated?",
  "What’s a traditional festival you think everyone should experience?",
  "How do you think social entrepreneurship impacts communities?",
  "What’s a global peace initiative you admire?",
  "How do you think language learning benefits global understanding?",
  "What’s a famous landmark with an interesting history?",
  "How do you think fashion sustainability can be improved?",
  "What’s a local delicacy you’d recommend to visitors?",
  "How do you think climate action can be more inclusive?",
  "What’s an indigenous culture you’d like to learn about?",
  "How do you think technology can support mental health?",
  "What’s a city known for its innovative architecture?",
  "How do you think global trade influences cultural exchange?",
  "What’s a traditional story or myth that intrigues you?",
  "How do you think community gardens impact neighborhoods?",
  "What’s a historical figure known for environmental activism?",
  "How do you think media literacy can be improved?",
  "What’s a country whose wildlife you’d love to see?",
  "How do you think cultural diversity benefits education?",
  "What’s a public art installation you admire?",
  "How do you think global pandemics shape societies?",
  "What’s a cultural custom that teaches respect?",
  "How do you think sports foster international friendship?",
  "What’s a natural resource that’s vital for your community?",
  "How do you think technology changes the way we travel?",
  "What’s a book that offers insight into another culture?",
  "How do you think urban planning affects social interactions?",
  "What’s a country with a rich musical heritage you enjoy?",
  "How do you think food festivals promote cultural understanding?",
  "What’s a historical event that shaped a nation?",
  "How do you think digital nomadism influences local economies?",
  "What’s a community project you’d like to participate in?",
  "How do you think film and cinema influence perceptions?",
  "What’s a place where you feel connected to history?",
  "How do you think environmental education can be improved?",
  "What’s a global charity that inspires you?",
  "How do you think urban wildlife can coexist with humans?",
  "What’s a language that’s at risk of disappearing?",
  "How do you think cultural festivals can promote peace?",
  "What’s a city that blends nature and urban life well?",
  "How do you think technology can help preserve endangered species?",
  "What’s a traditional craft you’d like to learn?",
  "How do you think social media influences cultural trends?",
  "What’s a natural habitat you want to protect?",
  "How do you think climate change impacts agriculture?",
  "What’s a country whose education system you admire?",
  "How do you think architecture reflects cultural values?",
  "What’s a historical era you find fascinating?",
  "How do you think art therapy helps mental health?",
  "What’s a local legend or folklore you enjoy?",
  "How do you think technology influences political engagement?",
  "What’s a documentary that broadened your perspective?",
  "How do you think renewable energy can reduce pollution?",
  "What’s a cuisine that represents cultural fusion?",
  "How do you think community festivals strengthen identity?",
  "What’s a wildlife conservation success story you know?",
  "How do you think global travel impacts cultural preservation?",
  "What’s a city with a rich literary history?",
  "How do you think food traditions evolve over time?",
  "What’s a place known for its natural beauty?",
  "How do you think education can promote environmental awareness?",
  "What’s a cultural practice you’d like to experience?",
  "How do you think digital platforms support artists?",
  "What’s a global challenge that requires collective action?",
  "How do you think cultural heritage sites can be protected?",
  "What’s a social issue you think needs more attention?",
  "How do you think climate change affects indigenous communities?",
  "What’s a festival that celebrates local traditions?",
  "How do you think technology changes the way we work?",
  "What’s a book that explores global cultures?",
  "How do you think urban green spaces affect health?",
  "What’s a form of traditional music you appreciate?",
  "How do you think education impacts social equality?",
  "What’s a country with diverse landscapes you want to visit?",
  "How do you think public art influences communities?",
  "What’s a wildlife species that symbolizes your country?",
  "How do you think climate action can be made more accessible?",
  "What’s a cultural festival you find exciting?",
  "How do you think digital innovation supports environmental efforts?",
  "What’s a city you think blends old and new cultures well?",
  "How do you think volunteering abroad changes perspectives?",
  "What’s a traditional dish that tells a story?",
  "How do you think cultural exchange programs benefit students?",
  "What’s a global environmental treaty you know?",
  "How do you think music influences social movements?",
  "What’s a natural landmark you’d love to explore?",
  "How do you think urbanization impacts cultural heritage?",
  "What’s a historical figure who advocated for social justice?",
  "How do you think technology affects human connections?",
  "What’s a city famous for its culinary scene?",
  "How do you think global warming impacts ocean life?",
  "What’s a cultural tradition that emphasizes family?",
  "How do you think arts education benefits children?",
  "What’s a natural ecosystem you want to learn more about?",
  "How do you think digital communication shapes identity?",
  "What’s a book that explores environmental issues?",
  "How do you think local markets support communities?",
  "What’s a global health crisis that affected your country?",
  "How do you think climate change affects migration patterns?",
  "What’s a traditional art form you admire?",
  "How do you think technology supports disaster relief?",
  "What’s a city with a unique architectural style?",
  "How do you think cultural diversity enriches cuisine?",
  "What’s a wildlife habitat under threat?",
  "How do you think education can foster global citizenship?",
  "What’s a documentary about nature that inspired you?",
  "How do you think social media influences activism?",
  "What’s a natural resource that’s crucial to your community?",
  "How do you think urban design can improve sustainability?",
  "What’s a cultural celebration that unites people?",
  "How do you think technology changes cultural preservation?",
  "What’s a famous historical site you want to visit?",
  "How do you think global trade affects local cultures?",
  "What’s a traditional story passed down in your family?",
  "How do you think environmental policies impact industries?",
  "What’s a country with a rich festival culture?",
  "How do you think digital tools help education access?",
  "What’s a natural phenomenon that fascinates you?",
  "How do you think community arts programs benefit neighborhoods?",
  "What’s a food that represents cultural identity?",
  "How do you think climate change affects food production?",
  "What’s a historical event that shaped your country?",
  "How do you think technology changes social activism?",
  "What’s a city you think balances tradition and innovation?",
  "How do you think cultural heritage influences personal identity?",
  "What’s a wildlife species important to your region?",
  "How do you think education can address environmental challenges?",
  "What’s a global environmental campaign you admire?",
  "How do you think music brings different cultures together?",
  "What’s a natural park or reserve you want to visit?",
  "How do you think urban spaces can be made more inclusive?",
  "What’s a traditional art or craft you’d like to learn?",
  "How do you think climate change affects biodiversity?",
  "What’s a cultural practice that emphasizes community?",
  "How do you think digital storytelling changes culture?",
  "What’s a city known for its green initiatives?",
  "How do you think education shapes cultural understanding?",
  "What’s a festival that celebrates environmental awareness?",
  "How do you think technology helps bridge cultural gaps?",
  "What’s a wildlife conservation effort you support?",
  "How do you think urban planning can protect natural habitats?",
  "What’s a global social movement you find inspiring?",
  "How do you think media can promote cultural empathy?",
  "What’s a natural wonder that you dream of seeing?",
  "How do you think climate change affects human health?",
  "What’s a traditional celebration that brings families together?",
  "How do you think arts and culture impact economic development?",
  "What’s a historic landmark in your country you cherish?",
  "How do you think technology influences cultural preservation?",
  "What’s a form of traditional music that moves you?",
  "How do you think education fosters creativity?",
  "What’s a global environmental challenge you want to help solve?",
  "How do you think urban gardens benefit cities?",
  "What’s a cultural exchange experience you’d like to have?",
  "How do you think social media can spread awareness about global issues?",
  "What’s a natural habitat that’s important to you?",
  "How do you think climate change impacts agriculture?",
  "What’s a local tradition you want to share with others?",
  "How do you think technology changes the way we celebrate?",
  "What’s a book that broadened your understanding of a culture?",
  "How do you think public art reflects community values?",
  "What’s a wildlife species you want to protect?",
  "How do you think education can combat environmental challenges?",
  "What’s a documentary about culture that inspired you?",
  "How do you think cultural diversity enriches society?",
  "What’s a city you find fascinating for its history?",
  "How do you think technology influences human rights activism?",
  "What’s a natural landscape you find beautiful?",
  "How do you think urban development can be sustainable?",
  "What’s a traditional food you enjoy?",
  "How do you think climate change affects global ecosystems?",
  "What’s a cultural heritage site you want to visit?",
  "How do you think arts education supports mental well-being?",
  "What’s a global social issue you want to understand better?",
  "How do you think technology helps in disaster management?",
  "What’s a community event you enjoy attending?",
  "How do you think cultural storytelling preserves history?",
  "What’s a wildlife species that symbolizes strength?",
  "How do you think urban green spaces promote health?",
  "What’s a festival that celebrates cultural diversity?",
  "How do you think education shapes future leaders?",
  "What’s a traditional art form that fascinates you?",
  "How do you think climate policies affect local communities?",
  "What’s a city known for its cultural heritage?",
  "How do you think technology changes social relationships?",
  "What’s a natural resource that’s vital globally?",
  "How do you think cultural exchange promotes peace?",
  "What’s a historic figure known for environmental work?",
  "How do you think urban design affects community well-being?",
  "What’s a festival that celebrates nature?",
  "How do you think technology supports education equity?",
  "What’s a local market that reflects cultural life?",
  "How do you think climate change impacts the arts?",
  "What’s a traditional story that teaches a life lesson?",
  "How do you think education can foster innovation?",
  "What’s a city you think is a cultural hub?",
  "How do you think social media affects cultural identity?",
  "What’s a wildlife sanctuary you’d like to visit?",
  "How do you think urbanization affects mental health?",
  "What’s a cultural tradition that teaches respect for nature?",
  "How do you think technology shapes future work culture?",
  "What’s a global environmental organization you know?",
  "How do you think arts programs benefit youth?",
  "What’s a natural wonder that inspires you?",
  "How do you think climate change affects social justice?",
  "What’s a traditional craft that needs preservation?",
  "How do you think education influences cultural values?",
  "What’s a city you find inspiring for its sustainability?",
  "How do you think technology impacts cultural preservation?",
  "What’s a cultural festival that brings communities together?",
  "How do you think social movements change culture?",
  "What’s a wildlife species important to indigenous cultures?",
  "How do you think urban green spaces foster social ties?",
  "What’s a historic landmark that tells a story?",
  "How do you think education supports environmental activism?",
  "What’s a local tradition you cherish?",
  "How do you think technology can help preserve languages?",
  "What’s a natural habitat important to biodiversity?",
  "How do you think cultural exchange enriches education?",
  "What’s a book that explores global environmental issues?",
  "How do you think urban planning can promote equity?",
  "What’s a traditional music style you enjoy?",
  "How do you think climate change affects ocean ecosystems?",
  "What’s a city you’d love to explore for its culture?",
  "How do you think technology impacts social justice movements?",
  "What’s a wildlife conservation effort that inspires you?",
  "How do you think arts and culture support community health?",
  "What’s a festival that celebrates indigenous culture?",
  "How do you think education can promote sustainability?",
  "What’s a global issue you want to take action on?",
  "How do you think technology shapes cultural expression?",
  "What’s a city that effectively balances tourism and local life?",
  "How do you think renewable energy adoption affects global politics?",
  "What’s a cultural custom that promotes community bonding?",
  "How do you think technology can help fight poverty?",
  "What’s a natural phenomenon unique to your region?",
  "How do you think global education systems can collaborate?",
  "What’s a historical monument you find fascinating?",
  "How do you think arts influence political change?",
  "What’s a traditional food that tells a story about its people?",
  "How do you think climate change impacts human migration?",
  "What’s a city famous for innovation in public transport?",
  "How do you think social media shapes public awareness?",
  "What’s a wildlife species that plays a key role in its ecosystem?",
  "How do you think urban green spaces can improve mental health?",
  "What’s a local art form that’s gaining international attention?",
  "How do you think education can be made more accessible worldwide?",
  "What’s a global initiative to protect endangered species?",
  "How do you think culture influences environmental attitudes?",
  "What’s a documentary that changed your perception of an issue?",
  "How do you think food culture reflects history and identity?",
  "What’s a city that is a model for sustainable living?",
  "How do you think technological advances affect cultural traditions?",
  "What’s a traditional craft that is at risk of disappearing?",
  "How do you think education prepares people for future challenges?",
  "What’s a natural park or reserve you want to volunteer at?",
  "How do you think urban farming can transform cities?",
  "What’s a festival that celebrates cultural diversity in your country?",
  "How do you think global trade affects local artisans?",
  "What’s a historical figure who inspired cultural unity?",
  "How do you think technology influences language preservation?",
  "What’s a wildlife conservation story that inspires hope?",
  "How do you think urban development impacts local ecosystems?",
  "What’s a cultural event you think promotes peace?",
  "How do you think social media campaigns affect environmental action?",
  "What’s a natural landmark you’d like to explore with friends?",
  "How do you think education shapes environmental responsibility?",
  "What’s a country you admire for its environmental policies?",
  "How do you think art can influence social awareness?",
  "What’s a traditional celebration you want to experience firsthand?",
  "How do you think technology can bridge cultural gaps?",
  "What’s a global health initiative you support?",
  "How do you think urban spaces can be redesigned for sustainability?",
  "What’s a cultural festival you think everyone should attend once?",
  "How do you think education impacts social justice?",
  "What’s a local cuisine that reflects your region’s history?",
  "How do you think technology can support disaster preparedness?",
  "What’s a wildlife species you’d like to learn more about?",
  "How do you think urbanization affects traditional lifestyles?",
  "What’s a cultural tradition that teaches resilience?",
  "How do you think renewable energy can reshape communities?",
  "What’s a city that has successfully preserved its cultural heritage?",
  "How do you think technology affects global communication?",
  "What’s a local environmental issue you’re concerned about?",
  "How do you think arts education promotes empathy?",
  "What’s a book or film that highlights cultural diversity?",
  "How do you think global cooperation can solve climate issues?",
  "What’s a festival that showcases indigenous cultures?",
  "How do you think technology can improve public health?",
  "What’s a historic site that offers lessons for the future?",
  "How do you think food traditions contribute to cultural identity?",
  "What’s a city you find inspiring for its green initiatives?",
  "How do you think education can foster innovation and creativity?",
  "What’s a documentary that explores environmental challenges?",
  "How do you think urban gardens improve community life?",
  "What’s a cultural art form that moved you emotionally?",
  "How do you think climate change affects coastal communities?",
  "What’s a traditional story that teaches important values?",
  "How do you think technology changes social activism?",
  "What’s a country whose natural beauty you admire?",
  "How do you think social media impacts cultural identity?",
  "What’s a wildlife habitat you want to help protect?",
  "How do you think urban design can promote sustainability?",
  "What’s a cultural practice that encourages environmental respect?",
  "How do you think education supports cultural understanding?",
  "What’s a city that blends history and modernity well?",
  "How do you think arts and culture contribute to economic growth?",
  "What’s a natural phenomenon that you find awe-inspiring?",
  "How do you think climate policies affect everyday life?",
  "What’s a traditional music genre you want to explore?",
  "How do you think education can address social inequality?",
  "What’s a city famous for its cultural festivals?",
  "How do you think technology can help preserve endangered languages?",
  "What’s a wildlife species that represents your country?",
  "How do you think urban green spaces affect public health?",
  "What’s a cultural celebration that brings communities together?",
  "How do you think social media influences environmental awareness?",
  "What’s a natural park or reserve you’d like to visit someday?",
  "How do you think education shapes future generations?",
  "What’s a global environmental campaign that inspires you?",
  "How do you think technology changes the way we connect?",
  "What’s a local tradition that reflects your culture?",
  "How do you think climate change impacts wildlife?",
  "What’s a historic event that shaped cultural identity?",
  "How do you think arts programs benefit youth development?",
  "What’s a documentary that opened your eyes to global issues?",
  "How do you think urban farming supports food security?",
  "What’s a cultural exchange you’d like to participate in?",
  "How do you think social media campaigns raise awareness?",
  "What’s a natural habitat you want to conserve?",
  "How do you think climate change affects global migration?",
  "What’s a traditional craft that you admire?",
  "How do you think education influences social change?",
  "What’s a city known for its artistic community?",
  "How do you think technology impacts human rights?",
  "What’s a wildlife sanctuary you want to support?",
  "How do you think urbanization affects cultural heritage?",
  "What’s a cultural festival that celebrates diversity?",
  "How do you think education can promote environmental stewardship?",
  "What’s a global issue that motivates you to take action?",
  "How do you think technology helps in crisis management?",
  "What’s a historic monument that teaches important lessons?",
  "How do you think food culture connects people worldwide?",
  "What’s a city famous for its innovation in sustainability?",
  "How do you think arts and culture promote social cohesion?",
  "What’s a natural wonder you dream of exploring?",
  "How do you think climate change affects agriculture?",
  "What’s a traditional dance or music style that fascinates you?",
  "How do you think education prepares people for a changing world?",
  "What’s a documentary about culture that inspired you?",
  "How do you think urban green spaces improve quality of life?",
  "What’s a cultural practice that teaches respect for the environment?",
  "How do you think technology influences cultural preservation?",
  "What’s a wildlife species that plays a key ecological role?",
  "How do you think education supports cultural diversity?",
  "What’s a city you admire for its balance of tradition and modernity?",
  "How do you think social media impacts cultural expression?",
  "What’s a local festival that showcases cultural heritage?",
  "How do you think climate action can be more inclusive?",
  "What’s a traditional food that symbolizes community?",
  "How do you think arts education benefits mental health?",
  "What’s a natural ecosystem that you want to protect?",
  "How do you think urban design can foster community connection?",
  "What’s a cultural event that promotes environmental awareness?",
  "How do you think technology changes social movements?",
  "What’s a city that serves as a cultural melting pot?",
  "How do you think education influences global citizenship?",
  "What’s a documentary about environmental issues that moved you?",
  "How do you think urban gardens impact food sustainability?",
  "What’s a wildlife conservation project you want to support?",
  "How do you think climate change affects human health?",
  "What’s a traditional story that teaches resilience?",
  "How do you think technology supports education access?",
  "What’s a city you’d like to visit for its cultural landmarks?",
  "How do you think arts programs can address social issues?",
  "What’s a natural phenomenon you find inspiring?",
  "How do you think climate policies impact local communities?",
  "What’s a cultural festival you’d love to experience?",
  "How do you think education fosters innovation?",
  "What’s a wildlife species important to your cultural identity?",
  "How do you think urban planning can improve environmental health?",
  "How do you politely say no to an invitation you don’t want to accept?"
];