const questionsPart4 = [
  "Imagine you found a time machine; where and when would you go first?",
  "If you were stranded on a deserted island, what three items would you want with you?",
  "Suppose you could live in any fictional world, which one would you choose?",
  "If you could switch lives with someone for a day, who would it be?",
  "Imagine you are the leader of a country; what’s the first law you would create?",
  "If you found a wallet on the street, what would you do?",
  "Suppose you could talk to animals; which animal would you talk to first?",
  "If you had to survive a zombie apocalypse, what would be your strategy?",
  "Imagine you could only eat one food for the rest of your life; what would it be?",
  "If you woke up as the opposite gender, what’s the first thing you would do?",
  "Suppose you could erase one memory from your past; would you do it? Why or why not?",
  "If you were invisible for a day, how would you use that ability?",
  "Imagine you had the chance to meet your future self; what questions would you ask?",
  "If you could live 100 years ago, how would your life be different?",
  "Suppose you discovered a secret door in your house; what’s behind it?",
  "If you had to choose between unlimited money or unlimited time, which would you pick?",
  "Imagine you’re a detective solving a mystery; what clues would you look for first?",
  "If you had the power to change one event in history, what would it be?",
  "Suppose you were given the ability to fly; how would your daily life change?",
  "If you could spend a day with any celebrity, who would it be and why?",
  "Imagine you find a magic lamp; what three wishes would you make?",
  "If you were an inventor, what would you create to make life easier?",
  "Suppose you were trapped in a video game; which game would you want it to be?",
  "If you could live forever but had to watch everyone else age, would you choose immortality?",
  "Imagine you found a letter from your future self; what advice might it contain?",
  "If you could change one thing about yourself, what would it be?",
  "Suppose you are given the chance to travel to Mars; would you go?",
  "If you were a character in a novel, what kind of story would it be?",
  "Imagine you had the power to heal others; how would you use it?",
  "If you could instantly learn any language, which would you choose?",
  "Suppose you could relive one day from your past; which day would it be?",
  "If you had a robot assistant, what tasks would you have it do?",
  "Imagine you were a superhero; what would your name and powers be?",
  "If you could visit any place in the world right now, where would you go?",
  "Suppose you found a secret passage in your school; where would it lead?",
  "If you could create a new holiday, what would it celebrate?",
  "Imagine you had the chance to apologize to someone from your past; who would it be?",
  "If you were an animal for a day, which would you be?",
  "Suppose you could swap homes with someone for a week; who would it be?",
  "If you found a treasure map, would you follow it?",
  "Imagine you woke up with the ability to speak any language fluently; how would you use it?",
  "If you could time travel to the future, what year would you visit?",
  "Suppose you could create a new invention; what problem would it solve?",
  "If you were the main character in a movie, what genre would it be?",
  "Imagine you were given three superpowers but could only keep one; which would you choose?",
  "If you could meet any historical figure, who would it be?",
  "Suppose you found a diary belonging to someone famous; what would you want to read?",
  "If you were invisible for an hour, what would you do?",
  "Imagine you had to live without the internet for a year; how would you cope?",
  "If you could change one law in your country, what would it be?",
  "Suppose you were stranded in a foreign country without money; what would you do?",
  "If you could become a master at any skill instantly, what would it be?",
  "Imagine you discovered you are royalty; how would your life change?",
  "If you could travel back to your childhood, what advice would you give yourself?",
  "Suppose you had a secret talent nobody knew about; what would it be?",
  "If you were a character in a fairy tale, what would your story be?",
  "Imagine you could create your dream job; what would it involve?",
  "If you found a mysterious object in your backyard, what would it be?",
  "Suppose you could live underwater for a day; what would you explore?",
  "If you could redesign your school, what changes would you make?",
  "Imagine you woke up in a different country; how would you find your way home?",
  "If you were a famous artist, what kind of art would you create?",
  "Suppose you were given the chance to erase one day from your life; would you do it?",
  "If you had to choose between being rich or famous, which would you pick?",
  "Imagine you could bring one fictional character to life; who would it be?",
  "If you were lost in a forest, what would you do to survive?",
  "Suppose you had the power to speak to plants; what would you ask them?",
  "If you could design your perfect home, what features would it have?",
  "Imagine you woke up with no memory; how would you figure out who you are?",
  "If you could live in a world without technology, what would be different?",
  "Suppose you were offered a ticket to anywhere in the universe; where would you go?",
  "If you were a famous musician, what genre would you perform?",
  "Imagine you had the power to solve one global problem; which would you choose?",
  "If you found a portal to another dimension, would you enter?",
  "Suppose you could speak to your past self; what warnings would you give?",
  "If you were the last person on Earth, what would you do?",
  "Imagine you could relive your favorite vacation; what would you do differently?",
  "If you could switch careers instantly, what would you try?",
  "Suppose you found out you have a twin you never knew about; how would you react?",
  "If you could create your own country, what laws would you implement?",
  "Imagine you had the ability to stop time; how would you use it?",
  "If you could live in any era of history, when would it be?",
  "Suppose you were a famous chef; what would your signature dish be?",
  "If you could invent a new sport, what would it involve?",
  "Imagine you woke up as an animal; how would you spend the day?",
  "If you could meet your future children, what advice would you give them?",
  "Suppose you could be invisible whenever you want; how would you use this power?",
  "If you had to choose between flying or breathing underwater, which would you pick?",
  "Imagine you could control the weather; what would you do with this power?",
  "If you were stranded on Mars, how would you survive?",
  "Suppose you discovered a new planet; what would you name it?",
  "If you could be the hero in any book, which would it be?",
  "Imagine you had a photographic memory; how would your life change?",
  "If you could instantly master any musical instrument, which would you choose?",
  "Suppose you could communicate with aliens; what questions would you ask?",
  "If you had the chance to live forever, would you take it? Why or why not?",
  "Imagine you could rewrite the ending of a movie; which one and how?",
  "If you could visit any place in your dreams, where would it be?",
  "Suppose you had to survive a week without modern technology; how would you prepare?",
  "If you could live one day as an animal, which would you choose and why?",
  "Imagine you find a mysterious key; what do you think it opens?",
  "If you were suddenly famous, how would you handle the attention?",
  "Suppose you are offered a chance to erase all your regrets; would you do it?",
  "If you could invent a gadget to solve one daily problem, what would it be?",
  "Imagine you meet an alien visitor; what would you say to them?",
  "If you were trapped in a haunted house, what would you do to escape?",
  "Suppose you could relive one important conversation; which would it be?",
  "If you had a clone, how would you use it?",
  "Imagine you discovered a hidden talent overnight; what would it be?",
  "If you woke up as a character in a fantasy novel, what role would you play?",
  "Suppose you could speak to your pet; what would you ask?",
  "If you were given a million dollars but had to spend it in one day, what would you do?",
  "Imagine you could change your name; what would you choose?",
  "If you found a message in a bottle, what would you hope it says?",
  "Suppose you could live under the sea for a week; what would you explore?",
  "If you could solve one mystery from history, which would it be?",
  "Imagine you had to give up one of your senses; which would you choose?",
  "If you could redesign your school curriculum, what subjects would you add?",
  "Suppose you could teleport anywhere instantly; where would you go first?",
  "If you woke up to find the world frozen in time, what would you do?",
  "Imagine you could talk to plants; what advice would they give?",
  "If you were stranded in a city you don’t know, how would you find help?",
  "Suppose you had to write a letter to your future self; what would you say?",
  "If you could be invisible for a day, how would you spend it?",
  "Imagine you found a secret garden; what would you do there?",
  "If you could live in any movie universe, which would it be?",
  "Suppose you had to survive without electricity for a month; how would you manage?",
  "If you could bring back one extinct animal, which would it be?",
  "Imagine you were a famous detective; what kind of cases would you solve?",
  "If you found a time capsule buried in your backyard, what would you hope to find?",
  "Suppose you could talk to your past self; what warning would you give?",
  "If you were granted three wishes, what would they be?",
  "Imagine you could live on another planet; what would daily life be like?",
  "If you woke up and everything was upside down, how would you react?",
  "Suppose you found a door to another world; would you enter?",
  "If you could relive your favorite childhood memory, which would it be?",
  "Imagine you were a character in a video game; what would your quest be?",
  "If you could master one skill overnight, which would you choose?",
  "Suppose you could change one thing about the world; what would it be?",
  "If you were the last person alive on Earth, what would you do?",
  "Imagine you found a magic pen that brings drawings to life; what would you create?",
  "If you had to spend a year living in the wilderness, what would you bring?",
  "Suppose you could instantly learn any language; how would you use this skill?",
  "If you were given a chance to redo one day, which day would it be?",
  "Imagine you could change your career path; what would you choose?",
  "If you had to choose between fame and happiness, which would you pick?",
  "Suppose you were offered a one-way ticket to space; would you go?",
  "If you could speak to animals, which would you talk to first?",
  "Imagine you woke up in a different country; how would you adapt?",
  "If you could change one thing about your personality, what would it be?",
  "Suppose you found a hidden treasure chest; what would you do with the contents?",
  "If you had the power to control the weather, how would you use it?",
  "Imagine you had a robot that could do any task; what would you assign?",
  "If you were a famous artist, what kind of art would you create?",
  "Suppose you could travel back in time to meet your ancestors; what would you ask?",
  "If you were stuck in an elevator with a stranger, how would you start a conversation?",
  "Imagine you could instantly heal any injury; how would you help others?",
  "If you had to live without your smartphone for a month, what would change?",
  "Suppose you found a secret passage in your home; where do you think it leads?",
  "If you could create your own country, what would its main values be?",
  "Imagine you had the chance to erase one global problem; which one?",
  "If you were the hero in a story, what would your quest be?",
  "Suppose you woke up one day as a different person; how would you react?",
  "If you could visit any planet, which one would you choose?",
  "Imagine you discovered you could talk to your future self; what would you ask?",
  "If you could redesign the internet, what changes would you make?",
  "Suppose you had to survive a week with no food delivery or restaurants; what would you cook?",
  "If you could swap lives with a fictional character, who would it be?",
  "Imagine you had to live in a world without music; how would it affect you?",
  "If you could invent a new holiday, what traditions would it include?",
  "Suppose you had the ability to read minds; how would you use this power?",
  "If you were a chef, what unique dish would you create?",
  "Imagine you had the power to bring one historical figure to life; who?",
  "If you could instantly travel anywhere in the world, where would you go?",
  "Suppose you were trapped in a snowstorm; how would you stay safe?",
  "If you had the choice to know the date of your death, would you want to?",
  "Imagine you could create your dream home; what features would it have?",
  "If you were the protagonist in a mystery novel, what clues would you look for?",
  "Suppose you found a magic mirror; what would you hope to see?",
  "If you could change one event in your life, what would it be?",
  "Imagine you had the power to make one wish come true; what would it be?",
  "If you could live underwater, what would your daily life look like?",
  "Suppose you were given the chance to speak to your pet’s thoughts; what would you ask?",
  "If you were stranded on a mountain, what three things would you want with you?",
  "Imagine you found a book that predicts the future; would you read it?",
  "If you could invent a machine that does anything, what would it do?",
  "Suppose you had the power to stop time for one hour daily; how would you use it?",
  "If you had to live in a different era, which would you choose?",
  "Imagine you were a character in a comedy; what role would you play?",
  "If you found a secret message in a bottle, what would you hope it says?",
  "Suppose you could live without sleep; how would you spend your extra time?",
  "If you could be a master of any sport, which would you pick?",
  "Imagine you could switch bodies with a friend for a day; what would you do?",
  "If you had the power to talk to plants, what would you ask them?",
  "Suppose you could live forever, but everyone else aged normally; would you choose immortality?",
  "If you were stranded on a desert island, what skills would help you survive?",
  "Imagine you found a portal to another dimension; would you enter?",
  "If you could relive any moment in history, which would you choose?",
  "Suppose you had the ability to fly; what would you do first?",
  "If you could erase one fear from your life, what would it be?",
  "Imagine you were given a blank check with unlimited funds; how would you spend it?",
  "If you had the choice to live in a futuristic city or a peaceful countryside, which would you pick?",
  "Suppose you discovered you have a secret admirer; how would you react?",
  "If you could invent a new musical instrument, what would it sound like?",
  "Imagine you woke up with no memory of your past; how would you find out who you are?",
  "If you could live in a storybook, which story would you choose?",
  "Suppose you had the ability to speak any language instantly; how would you use it?",
  "If you could travel through time but only once, where would you go?",
  "Imagine you found a treasure map; what adventure would you embark on?",
  "If you could change one law in your country, what would it be?",
  "Suppose you had the power to bring your favorite fictional character to life; who?",
  "If you were given the chance to start a new life in a different country, would you?",
  "Imagine you had the power to make everyone happy for one day; what would you do?",
  "If you could live without any electronic devices for a month, how would you manage?",
  "Suppose you found a diary from the future; what would you hope it says?",
  "If you could invent a new technology, what problem would it solve?",
  "Imagine you were the ruler of a kingdom; what kind of leader would you be?",
  "If you could be any mythical creature, which would you choose?",
  "Suppose you were lost in a forest at night; how would you survive?",
  "If you could bring back one extinct species, which would it be?",
  "Imagine you could create your own language; what would it sound like?",
  "If you had to live in a world without books, how would you learn?",
  "Suppose you could speak to your future self; what advice would you ask for?",
  "If you could change one thing about your personality, what would it be?",
  "Imagine you had the power to control dreams; what would you dream about?",
  "If you were given a chance to live on the moon, would you take it?",
  "Suppose you found a hidden room in your house; what would you do?",
  "If you could invent a new holiday, what traditions would it include?",
  "Imagine you could speak to animals; which one would you talk to first?",
  "If you were stranded on an island with only one other person, who would you want it to be?",
  "Suppose you could instantly become an expert in any field; which would you choose?",
  "If you could live in any decade of the 20th century, which would it be?",
  "Imagine you woke up as a famous athlete; how would your life change?",
  "If you could have dinner with any historical figure, who would it be?",
  "Suppose you found a magic lamp; what three wishes would you make?",
  "If you could live in a world of magic, what kind of magic would you use?",
  "Imagine you were a character in a horror movie; how would you survive?",
  "If you could change the ending of a book or movie, which one and how?",
  "Suppose you could visit any place in the universe; where would you go?",
  "If you found out you were a descendant of royalty, how would you react?",
  "Imagine you had the power to heal any illness; who would you help first?",
  "If you were a famous chef, what dish would you be known for?",
  "Suppose you could live in any fictional city; which would you choose?",
  "If you had to choose between being rich or famous, which would you pick?",
  "Imagine you were an inventor; what would you create?",
  "If you could switch places with your best friend for a day, what would you do?",
  "Suppose you were trapped in a snowstorm; how would you keep warm?",
  "If you could relive your happiest memory, which one would it be?",
  "Imagine you found a secret message in an old book; what would it say?",
  "If you could live without sleep, what would you do with the extra time?",
  "Suppose you had the power to stop time; how would you use it?",
  "If you could talk to your past self, what advice would you give?",
  "Imagine you were stranded in a desert; how would you survive?",
  "If you had a time machine, would you visit the past or future?",
  "Suppose you found a magic potion; what effect would you want it to have?",
  "If you could instantly master any musical instrument, which would you choose?",
  "Imagine you had the ability to talk to plants; what would they say?",
  "If you could change one thing about the world, what would it be?",
  "Suppose you were a character in a comedy show; what would your role be?",
  "If you could live in a world without technology, what would life be like?",
  "Imagine you were offered a ticket to travel anywhere; where would you go?",
  "If you could be invisible for a day, what would you do?",
  "Suppose you found a treasure chest; what would you hope to find inside?",
  "If you could relive any year of your life, which would you choose?",
  "Imagine you woke up with the power to control the weather; what would you do?",
  "If you could live in any country for a year, where would you go?",
  "Suppose you could switch careers instantly; what would you choose?",
  "If you had to survive a natural disaster, how would you prepare?",
  "Imagine you found a secret passage in your school; where would it lead?",
  "If you could create a new sport, what would it be like?",
  "Suppose you had the power to grant wishes; how would you use it?",
  "If you could live as any animal for a day, which would you pick?",
  "Imagine you could meet your future self; what would you ask?",
  "If you were stranded on a mountain, what three things would you want?",
  "Suppose you found a magic mirror; what would you hope to see?",
  "If you could live without one of your five senses, which would you choose?",
  "Imagine you could travel to any fictional world; where would you go?",
  "If you had the chance to change one thing in your past, what would it be?",
  "Suppose you could speak to any historical figure; who would you choose?",
  "If you were the main character in a sci-fi movie, what would your mission be?",
  "Imagine you had the power to read minds; how would you handle it?",
  "If you could invent a device to make life easier, what would it be?",
  "Suppose you were trapped in a maze; how would you find your way out?",
  "If you could live underwater, what would you explore first?",
  "Imagine you found a portal to the past; what event would you witness?",
  "If you could live without social media, how would your life change?",
  "Suppose you had to give up your favorite food for a year; how would you cope?",
  "If you could instantly learn any skill, what would you choose?",
  "Imagine you were a character in a fairy tale; what kind of story would it be?",
  "If you had the power to change your appearance, how would you look?",
  "Suppose you found a lost puppy; what would you do?",
  "If you could live in any season year-round, which would you choose?",
  "Imagine you could time travel but only for 10 minutes; what would you do?",
  "If you could live without money for a month, how would you manage?",
  "Suppose you found a mysterious book; what secrets would it hold?",
  "If you could invent a new holiday, what would it celebrate?",
  "Imagine you could talk to ghosts; what would you ask?",
  "If you were given a chance to be invisible, what would you do?",
  "Suppose you were offered a chance to explore outer space; would you accept?",
  "If you could rewrite one moment in history, what would you change?",
  "Suppose you woke up in a different body; how would you adjust?",
  "If you could have dinner with any fictional character, who would it be?",
  "Imagine you found a secret message hidden in a painting; what would it say?",
  "If you could invent a machine that reads thoughts, how would society change?",
  "Suppose you could live forever but never form new relationships; would you choose immortality?",
  "If you had to choose between living in a big city or the countryside forever, which would you pick?",
  "Imagine you discovered you had a hidden talent for something unusual; what is it?",
  "If you could erase one global problem overnight, what would it be?",
  "Suppose you were given the ability to breathe underwater; how would you explore?",
  "If you had to choose a new name for yourself, what would it be?",
  "Imagine you could change one law to improve your country; what would you change?",
  "If you were stranded in a foreign country without knowing the language, how would you survive?",
  "Suppose you found a diary that predicted the future; would you read it?",
  "If you could meet your childhood hero, what would you say?",
  "Imagine you woke up in a world where everyone tells the truth all the time; what would happen?",
  "If you could create your own perfect day, what would it look like?",
  "Suppose you had the power to teleport anywhere instantly; how would you use it daily?",
  "If you could live a week as a famous person, who would it be?",
  "Imagine you found a magic paintbrush; what would you create?",
  "If you could relive your favorite holiday, which would it be?",
  "Suppose you had the power to heal any emotional pain; how would you help others?",
  "If you could live without sleep for a year, what would you do with the extra time?",
  "Imagine you had the ability to speak any language; how would you use this power?",
  "If you had to live in a world without music, how would you cope?",
  "Suppose you were trapped in a video game; what kind of game would you want it to be?",
  "If you could change one thing about the education system, what would it be?",
  "Imagine you woke up with the ability to control fire; how would you use it?",
  "If you were given the chance to colonize a new planet, what rules would you set?",
  "Suppose you could bring back one extinct plant species; which would you choose?",
  "If you found a letter from your future self, what advice would you expect?",
  "Imagine you could design a perfect city; what features would it have?",
  "If you had to choose between having unlimited money or unlimited knowledge, which would you pick?",
  "Suppose you discovered a hidden talent for dancing; how would you use it?",
  "If you could live in a world where no one lied, how would life be different?",
  "Imagine you had the power to stop natural disasters; how would you use it?",
  "If you were given the ability to communicate with animals, which would you talk to first?",
  "Suppose you could create a new form of art; what would it look like?",
  "If you had to spend a year without modern technology, how would you adapt?",
  "Imagine you found a hidden treasure in your backyard; what would you do?",
  "If you could live forever but had to watch your loved ones age, would you accept?",
  "Suppose you could change one thing about your personality instantly; what would it be?",
  "If you were a character in a historical drama, what era would you live in?",
  "Imagine you had the power to erase all negativity from the world; what challenges might arise?",
  "If you could invent a device to read minds, would you use it?",
  "Suppose you could live in a virtual reality world of your choice; what would it be like?",
  "If you had to survive a week in the wilderness alone, what skills would be most important?",
  "Imagine you could talk to your future children; what would you want to tell them?",
  "If you could live without any stress for a month, how would you spend your time?",
  "Suppose you could bring one fictional technology to real life; which would you choose?",
  "If you could switch places with a historical figure for a day, who would it be?",
  "Imagine you found a book that wrote itself based on your thoughts; what story would it tell?",
  "If you could live in a world with no money, how would society work?",
  "Suppose you were given the chance to restart your life at any age; when would you choose?",
  "If you could invent a machine to solve climate change, what would it do?",
  "Imagine you woke up in a world where everyone could fly; how would that change things?",
  "If you were stranded on an island with only one book, what would it be?",
  "Suppose you could live without fear; how would your life change?",
  "If you could meet your ancestors, what would you want to know?",
  "Imagine you had the power to bring dreams to life; what would you create?",
  "If you could live in any fictional kingdom, which would you choose?",
  "Suppose you had the ability to see the future; how would you handle it?",
  "If you could change one event in your country’s history, what would it be?",
  "Imagine you found a portal that leads to a parallel universe; would you explore?",
  "If you were the captain of a spaceship, where would you go?",
  "Suppose you could create your own religion; what would be its core beliefs?",
  "If you had to live without one of your five senses, which would you give up?",
  "Imagine you could instantly become fluent in any musical instrument; which would you pick?",
  "If you could live in a world where everyone was honest, how would that affect relationships?",
  "Suppose you were given the chance to erase one memory; would you do it?",
  "If you found a map to a secret treasure, would you follow it?",
  "Imagine you had the ability to bring peace to any conflict; how would you use it?",
  "If you could invent a new kind of transportation, what would it be?",
  "Suppose you woke up one day in a completely different culture; how would you adapt?",
  "If you could live in any city in the world, where would it be?",
  "Imagine you had the power to change the past; what would you do first?",
  "If you could communicate with extraterrestrials, what questions would you ask?",
  "Suppose you had the ability to heal yourself instantly; how would you use it?",
  "If you were given the opportunity to colonize another planet, what would you bring?",
  "Imagine you could live without needing food or water; how would your lifestyle change?",
  "If you could create a utopian society, what would be its key features?",
  "Suppose you found a secret underground city; what would you do?",
  "If you could switch minds with any person for a day, who would it be?",
  "Imagine you were a character in a dystopian novel; how would you survive?",
  "If you could invent a device that translates animal speech, how would you use it?",
  "Suppose you could live without the internet; what hobbies would you take up?",
  "If you could create your own mythology, what creatures would be in it?",
  "Imagine you had the ability to control dreams; what would you dream about?",
  "If you were stranded on an alien planet, how would you adapt?",
  "Suppose you could relive one year of your life; which would it be?",
  "If you had the power to change one thing about humanity, what would it be?",
  "Imagine you were given the task to write the future history of Earth; what would you include?",
  "If you could live in any historical event, which would you choose?",
  "Suppose you had the power to erase all lies from the world; what would happen?",
  "If you could live without needing sleep, what would you do with the extra time?",
  "Imagine you found a magic compass; where would it lead you?",
  "If you could create a new holiday that everyone celebrates, what would it be?",
  "Suppose you could be invisible anytime you want; how would you use this power?",
  "If you could bring one book character into the real world, who would it be?",
  "Imagine you could time travel but only once; would you go to the past or future?",
  "If you could live forever, but could never leave your hometown, would you choose immortality?",
  "Suppose you found a magic potion that grants intelligence; would you drink it?",
  "If you could speak every language on Earth, how would you use this ability?",
  "Imagine you woke up one day with no memory of your identity; how would you find out who you are?",
  "If you could design your dream house anywhere in the world, where would it be?",
  "Suppose you could live without any digital devices for a year; what would you do?",
  "If you could create your own ideal society, what rules would it have?",
  "Imagine you found a portal to your favorite fictional world; would you enter?",
  "If you were the leader of a country, what would be your first decision?",
  "Suppose you had to live without speaking for a month; how would you communicate?",
  "If you could choose to be famous or anonymous, which would you pick?",
  "Imagine you could master any art form instantly; what would you create?",
  "If you could change one thing about your childhood, what would it be?",
  "Suppose you could meet yourself from 10 years ago; what would you say?",
  "If you could have any superpower but only use it once, what would it be?",
  "Imagine you were the main character in a thriller; how would you survive?",
  "If you could live in any fictional city, which would it be?",
  "Suppose you could bring any extinct animal back to life; which would you choose?",
  "If you were given the chance to erase all suffering in the world, would you?",
  "Imagine you had the power to see everyone’s thoughts for one day; what would you learn?",
  "If you could create a new type of music, what would it sound like?",
  "Suppose you found a secret diary of a famous person; what would you look for?",
  "If you had to live without one sense, which would you give up?",
  "Imagine you could travel back in time to witness one event; which would you pick?",
  "If you could live in a world without money, how would you survive?",
  "Suppose you could live as a character in a comedy; what role would you play?",
  "If you could invent a device that controls the weather, how would you use it?",
  "Imagine you had to survive a natural disaster; what would be your plan?",
  "If you could switch places with a celebrity for a week, who would it be?",
  "Suppose you had to spend a year in complete isolation; how would you cope?",
  "If you found a magic book that grants knowledge, what would you learn first?",
  "Imagine you could live in any country for a year; where would you go?",
  "If you could be a master of any sport, which would you choose?",
  "Suppose you were stranded on a deserted island; what three things would you bring?",
  "If you had the power to change one thing about society, what would it be?",
  "Imagine you could live underwater for a month; what would you discover?",
  "If you could invent a new language, what would it sound like?",
  "Suppose you could speak to your future self; what questions would you ask?",
  "If you could erase one fear from your life, what would it be?",
  "Imagine you were the last human on Earth; how would you live?",
  "If you could have dinner with any historical figure, who would it be?",
  "Suppose you could instantly learn any skill; what would you pick?",
  "If you had the power to make everyone happy for a day, what would you do?",
  "Imagine you found a secret garden; what would you plant?",
  "If you could live in a world with no technology, how would life be different?",
  "Suppose you had the power to bring one fictional character to life; who?",
  "If you could visit any planet in our solar system, which would you pick?",
  "Imagine you woke up with the ability to control time; what would you do?",
  "If you could live without internet for a month, how would you spend your time?",
  "Suppose you found a treasure chest; what would you hope to find inside?",
  "If you could live forever but had to watch everyone you love age and die, would you?",
  "Imagine you could create your own perfect day; what would it include?",
  "If you could be any mythical creature, which would you be?",
  "Suppose you could travel to any fictional world; where would you go?",
  "If you were the hero in a story, what would your quest be?",
  "Imagine you could talk to animals; which would you choose first?",
  "If you could invent a new holiday, what would it celebrate?",
  "Suppose you found a secret message hidden in an old book; what would it say?",
  "If you could live in any era of history, which would you pick?",
  "Imagine you had the power to stop time for one hour; what would you do?",
  "If you could change one law in your country, what would it be?",
  "Suppose you could be invisible whenever you wanted; how would you use this power?",
  "If you could meet any fictional character, who would it be?",
  "Imagine you found a portal to another dimension; would you enter?",
  "If you could relive one day of your life, which would it be?",
  "Suppose you had to survive a week without food delivery or restaurants; how would you manage?",
  "If you could switch lives with someone for a day, who would it be?",
  "Imagine you woke up as the opposite gender; what would you do first?",
  "If you could create a new invention, what problem would it solve?",
  "Suppose you found a letter from your future self; what would it say?",
  "If you could live in a world without money, how would you survive?",
  "Imagine you had the power to control dreams; what would you dream about?",
  "If you were stranded on an alien planet, how would you survive?",
  "Suppose you could bring one extinct animal back to life; which would you choose?",
  "If you could instantly learn any language, which would you pick?",
  "Imagine you had the ability to heal any illness; who would you help first?",
  "If you could change one thing about your past, what would it be?",
  "Suppose you found a magic lamp; what three wishes would you make?",
  "If you could live in any fictional city, which would you choose?",
  "Imagine you had the power to make everyone tell the truth; what would happen?",
  "If you could be any character in a movie, who would you be?",
  "Suppose you found a secret door in your house; where would it lead?",
  "If you could be invisible for an hour, what would you do?",
  "Imagine you woke up with no memory; how would you discover who you are?",
  "If you could create your own perfect society, what rules would it have?",
  "Suppose you had the ability to read minds; how would you use it?",
  "If you could switch careers instantly, what would you choose?",
  "Imagine you found a portal to the past; what event would you witness?",
  "If you could live in a world without music, how would it affect you?",
  "Suppose you could invent a new sport; what would it be?",
  "If you could bring back one person from history to life, who would it be?",
  "Imagine you had the power to control the weather; what would you do?",
  "If you could live in any country for a year, where would you go?",
  "Suppose you could talk to your pet; what would you ask?",
  "If you were given three wishes, what would they be?",
  "Imagine you woke up in a different time period; how would you adapt?",
  "If you could invent a machine that does anything, what would it do?",
  "Suppose you were stranded in a snowstorm; how would you survive?",
  "If you could change one thing about humanity, what would it be?",
  "Imagine you had the power to bring peace to the world; how would you do it?",
  "What’s your favorite thing to eat for breakfast?"
];