const questionsPart7 = [
  "What’s the silliest thing that made you laugh recently?",
  "If your life were a movie, what would the title be?",
  "What’s your favorite guilty pleasure snack?",
  "If animals could talk, which one would be the funniest?",
  "What’s a fictional world you’d love to visit?",
  "What’s the weirdest food combination you actually like?",
  "If you could be a character from any TV show, who would you be?",
  "What song do you secretly sing at the top of your lungs when alone?",
  "If you had a time machine but could only use it once, when would you go?",
  "What would your dream treehouse look like?",
  "If you were a dessert, what kind would you be?",
  "What's your go-to dance move?",
  "What’s the funniest thing you believed as a kid?",
  "If you had a personal mascot, what would it be?",
  "What’s your favorite pun or joke?",
  "If your pet had a secret life, what do you think it would be?",
  "If you were an emoji, which one would you be and why?",
  "What’s a fun fact that always surprises people?",
  "If you could only wear one outfit forever, what would it be?",
  "What’s your favorite way to waste time?",
  "If you had to eat one food for the rest of your life, what would it be?",
  "If your bed could transport you anywhere when you fall asleep, where would you go tonight?",
  "What’s the worst haircut you ever had?",
  "What’s the funniest nickname you’ve ever had?",
  "If you could live in any cartoon universe, which one would it be?",
  "What’s something totally useless that you’re really good at?",
  "What fictional animal would you want as a pet?",
  "If you opened a restaurant, what kind of food would you serve and what would you name it?",
  "If you could talk to one type of object (like plants or machines), what would it be?",
  "What game did you love as a child that you’d still play today?",
  "If your mood today were a color, what color would it be?",
  "If you could instantly learn any one silly talent (like juggling or yodeling), what would it be?",
  "What’s your favorite ice cream topping combo?",
  "If you were a mythical creature, which one would you be?",
  "What would your superhero weakness be?",
  "What’s the most ridiculous thing you’ve ever googled?",
  "If you were a villain, what would your silly evil plan be?",
  "What’s a movie you secretly love that no one expects?",
  "What’s your go-to karaoke song?",
  "If you were famous for something unusual, what would it be?",
  "What’s your favorite board game or card game to play just for laughs?",
  "If your favorite drink had a personality, what would it be like?",
  "If you had to swap lives with a cartoon character for a day, who would you pick?",
  "What’s your idea of the perfect lazy day?",
  "What food do you wish could be calorie-free forever?",
  "What would be your silly catchphrase?",
  "If your name had to rhyme with your favorite animal, what would it be?",
  "What’s your ultimate comfort TV show or movie?",
  "If you could have dinner with any fictional character, who would it be?",
  "What’s a weird food combination you secretly enjoy?",
  "If you could instantly master any instrument, which would it be?",
  "What’s a silly fear you had as a child?",
  "If you could live in any fictional world, where would you choose?",
  "What cartoon character do you relate to the most?",
  "What’s the most random fun fact you know?",
  "If animals could talk, which one would be the funniest?",
  "What’s your go-to karaoke song?",
  "Have you ever laughed so hard you cried? What caused it?",
  "What’s the most unusual item in your room right now?",
  "If your life were a movie, what would the title be?",
  "Which game (board, video, or sport) brings out your competitive side?",
  "What’s your favorite type of dessert and why?",
  "Would you rather always be slightly late or extremely early?",
  "If you could swap lives with a celebrity for a day, who would it be?",
  "What's your favorite guilty pleasure show or movie?",
  "If your pet could suddenly speak, what’s the first thing they’d say?",
  "What’s a nickname you've had that made you laugh?",
  "What’s the weirdest dream you remember?",
  "If you could have any useless superpower, what would it be?",
  "Which emoji do you overuse?",
  "If you had a personal robot, what task would you assign it?",
  "Would you rather have a rewind or pause button for your day?",
  "What’s the silliest thing you believed growing up?",
  "If you could invent a holiday, what would people celebrate?",
  "What’s your favorite ice cream flavor?",
  "If you could have any animal as a pet (safely), what would you pick?",
  "What fashion trend do you secretly love or hate?",
  "What was your favorite toy or game as a kid?",
  "What’s a sound or smell that makes you instantly nostalgic?",
  "If your laugh had a sound effect, what would it be?",
  "What’s a talent you wish you had just for fun?",
  "What was your go-to school lunch or snack?",
  "If you had to eat one meal forever, what would it be?",
  "What’s a word you love the sound of?",
  "If you could teleport anywhere for a weekend, where would you go?",
  "What’s the most fun class you ever took?",
  "What’s something that always makes you giggle, no matter your mood?",
  "What silly rumor or myth did you used to believe?",
  "Would you rather talk like a pirate or walk like a robot for a day?",
  "What’s your dream amusement park ride?",
  "If you opened a restaurant, what would it serve and be called?",
  "What’s the most random item on your bucket list?",
  "What’s your signature dance move?",
  "Would you rather always have to rhyme when speaking or sing instead of talk?",
  "If you were a dessert, what would you be and why?",
  "What’s your favorite childhood joke or riddle?",
  "If you could prank anyone without consequences, who would it be?",
  "What’s your favorite thing to do when you’re bored?",
  "Would you rather have spaghetti hair or marshmallow fingers?",
  "If you were a flavor, what would you taste like?",
  "What’s a silly superstition you secretly follow?",
  "If your shoes could talk, what would they say about your adventures?",
  "What’s the worst haircut you ever had?",
  "What would your theme song be every time you enter a room?",
  "What would you name a pet dinosaur?",
  "What’s a ridiculous law you’d create if you were president for a day?",
  "Would you rather hiccup every time you speak or sneeze when you laugh?",
  "If you were a kitchen utensil, which one would you be?",
  "What’s the funniest outfit you’ve ever worn?",
  "If you had to wear a costume every day, what would it be?",
  "What’s a dance you wish you could do perfectly?",
  "If you were turned into a cartoon animal, what would you look like?",
  "What’s the weirdest snack combo you’ve tried?",
  "What’s the most awkward autocorrect mistake you’ve made?",
  "If aliens visited you, what snack would you offer them?",
  "Would you rather be a famous meme or a viral TikTok star?",
  "What would your dream treehouse include?",
  "If you could rename the days of the week, what would you call Monday?",
  "What’s the most unusual compliment you’ve ever received?",
  "What’s a song lyric you always misheard?",
  "What’s the most outrageous dare you’ve accepted?",
  "What’s your favorite word in another language?",
  "If your favorite food had a theme song, what would it sound like?",
  "What’s the weirdest way you’ve injured yourself?",
  "What fictional character would be the worst roommate?",
  "Would you rather sleep in a hammock or a bunk bed forever?",
  "What’s a sound that instantly makes you laugh?",
  "If you had to give up one of your senses for a week, which would you pick?",
  "What’s a conspiracy theory you think is kind of funny?",
  "If you had your own talk show, what would it be called?",
  "What’s a snack you always secretly save for last?",
  "What’s the funniest name you’ve ever seen someone give their pet?",
  "If you could design your own emoji, what would it look like?",
  "What’s the best joke you’ve heard recently?",
  "Would you rather be able to speak in movie quotes or song lyrics only?",
  "If your favorite hobby became an Olympic sport, how would you score?",
  "What’s your ideal breakfast in bed?",
  "If clouds tasted like something, what should they taste like?",
  "What’s a made-up sport you wish existed?",
  "If you had to live in a vending machine, what would you stock around you?",
  "What’s the most bizarre dream vacation you can imagine?",
  "Would you rather fight one horse-sized duck or a hundred duck-sized horses?",
  "What’s the most creative excuse you’ve used for being late?",
  "What movie would be hilarious with you in the lead role?",
  "What song do you sing in the shower but never in public?",
  "What’s a toy from your childhood you wish you still had?",
  "Would you rather always wear mismatched socks or inside-out shirts?",
  "What would your pirate name be?",
  "What’s something people find annoying that you secretly enjoy?",
  "What would your dream amusement park look like?",
  "If you could have any animal as a pet (real or mythical), what would it be?",
  "What’s the weirdest food you actually enjoy?",
  "If you were a character in a video game, what would be your special power?",
  "What’s a silly fear you had as a child?",
  "If you could swap lives with a cartoon character for a day, who would it be?",
  "What’s a sound that instantly makes you smile?",
  "If your laugh had a color, what color would it be?",
  "What’s the most ridiculous fashion trend you ever tried?",
  "If your life had a jingle, how would it go?",
  "What’s your go-to karaoke song?",
  "If you had a boat, what would you name it?",
  "What’s a funny nickname someone once gave you?",
  "If you could be a guest on any TV show, past or present, which would it be?",
  "What’s something totally useless you’re amazing at?",
  "If you could invent a holiday, what would it celebrate?",
  "What’s a food you secretly dislike but pretend to like?",
  "What’s the most fun you’ve ever had doing absolutely nothing?",
  "If your pet could talk, what would it say about you?",
  "If you could turn anything into chocolate, what would you choose?",
  "What’s your most memorable birthday party?",
  "If your favorite movie had a blooper reel of your life, what would be in it?",
  "What’s the best prank you’ve ever pulled (or had pulled on you)?",
  "What’s the goofiest gift you've ever received?",
  "What’s a talent show act you would never dare to perform?",
  "If you had to wear one costume forever, what would it be?",
  "What’s the weirdest dream you can remember?",
  "What’s a fake job title you wish existed just for you?",
  "If your voice changed to sound like a celebrity’s, whose voice would you want?",
  "What’s your favorite cheesy joke or pun?",
  "What’s the most bizarre excuse you’ve used to get out of something?",
  "If you had your own soda flavor, what would it taste like?",
  "What’s a silly superstition you’ve heard or believed in?",
  "If you could rename the days of the week, what would you call them?",
  "What’s something you’ve always wanted to try, just for laughs?",
  "If you had a silly walk, what would it look like?",
  "What’s your guilty pleasure snack combo?",
  "If your furniture could talk, what would your couch say?",
  "What’s a song lyric that always makes you laugh?",
  "If you could make any object in your house talk, which would it be?",
  "What’s the most outrageous thing you’ve done for a dare?",
  "What’s a totally fictional gadget you wish was real?",
  "If you had a fan club, what would they be called?",
  "What’s something fun you’d put in your dream treehouse?",
  "If your shadow had a personality, what would it be like?",
  "What’s the worst pickup line you've ever heard or used?",
  "If your hair had a mind of its own, what would it want?",
  "What’s a silly competition you’d win gold in?",
  "What’s something you laugh at that no one else seems to find funny?",
  "If your thoughts were a TV channel, what kind of show would be airing today?",
  "What’s a food that you think would be hilarious to eat with chopsticks?",
  "If you could time travel for snacks only, where would you go?",
  "What’s your secret dance move when no one is watching?",
  "What’s a prank idea that’s funny but harmless?",
  "If you could turn any household object into a robot helper, what would you choose?",
  "What’s a sound that never fails to make you giggle?",
  "If you had a comedy stage name, what would it be?",
  "What would be your theme song when entering a room?",
  "What’s a totally random hobby you wish you were great at?",
  "What’s the goofiest way to say goodbye you can think of?",
  "If your phone had a personality, what would it say about how you use it?",
  "What’s a dance move you’ve always wanted to master just for fun?",
  "What’s something strange you’ve collected (or wish you did)?",
  "What’s the silliest thing you believed as a kid?",
  "If your life were a sitcom, what would its title be?",
  "What animal do you secretly think acts just like you?",
  "What’s the most dramatic way you’ve ever reacted to a small inconvenience?",
  "If you could make a movie starring only animals, what would the plot be?",
  "What’s a silly app idea you’d want to make?",
  "What’s a nonsense word you secretly love to say?",
  "If your personality were a dessert, what would it be?",
  "What’s the silliest argument you’ve ever had?",
  "If your laugh were an emoji, which one would it be?",
  "What’s a funny misunderstanding you’ve had recently?",
  "What’s the weirdest reason you’ve ever missed an appointment or meeting?",
  "If socks could talk, what would yours say after a long day?",
  "What’s the most random compliment you’ve received?",
  "If you had to host a game show, what kind would it be?",
  "What’s a funny tradition you wish your family had?",
  "What’s the quirkiest thing you do every day without thinking?",
  "What’s a completely made-up award you’d like to win?",
  "If your life had a laugh track, when would it play the most?",
  "What’s a funny title you’d give your autobiography?",
  "What’s the weirdest gift you’ve ever given?",
  "If you could invent a new color, what would it be called?",
  "What’s a snack you’ve invented or combined yourself?",
  "If you could turn your favorite emoji into a real object, which one would it be?",
  "What’s the oddest compliment you’ve ever heard someone say?",
  "What’s the goofiest way you’ve tried to impress someone?",
  "If aliens watched your daily routine, what would they find the funniest?",
  "What’s a food you’ve dropped but still ate?",
  "If your backpack/purse had a secret power, what would it be?",
  "What’s your secret talent in doing something totally unnecessary?",
  "What’s the funniest way you’ve ever injured yourself?",
  "What’s a dance style you’d love to invent?",
  "If your pet had a YouTube channel, what would it be called?",
  "What’s a funny lie you believed way too long?",
  "What’s the most random object you carry around?",
  "What’s your dream “useless invention”?",
  "What’s your favorite sound that’s oddly satisfying?",
  "Do you believe animals have a sense of humor?",
  "If you could have a personal theme song, what would it be?",
  "Have you ever laughed so hard you cried?",
  "What’s your go-to dance move when no one is watching?",
  "If you could swap lives with a cartoon character, who would it be?",
  "What’s your guilty pleasure snack?",
  "If you had a pet dinosaur, what would you name it?",
  "Would you rather fight one giant duck or a hundred duck-sized horses?",
  "What’s your favorite childhood toy or game?",
  "What movie do you secretly love but rarely admit?",
  "Have you ever created a fake name for fun?",
  "What’s the weirdest talent you have?",
  "Do you talk to your plants or pets?",
  "What’s your most memorable birthday moment?",
  "If you were a fruit, what fruit would you be and why?",
  "Have you ever tried to learn a magic trick?",
  "What’s your favorite pun or dad joke?",
  "If you could teleport to any place right now, where would you go?",
  "What’s your most irrational fear that makes you laugh in hindsight?",
  "What’s the silliest thing you believed as a kid?",
  "What animal would you choose to be your sidekick?",
  "Do you believe in aliens just a little?",
  "What’s your dream carnival food combo?",
  "Have you ever tried to write a song or a poem just for fun?",
  "Would you survive in a zombie apocalypse?",
  "Do you enjoy watching blooper reels or outtakes?",
  "What’s your favorite emoji and why?",
  "What’s a food you hated as a kid but love now?",
  "What’s your go-to karaoke song?",
  "Have you ever invented a game just to pass the time?",
  "Would you rather wear socks on your hands or mittens on your feet?",
  "If you could have a talking animal friend, which one would you choose?",
  "Have you ever taken a ridiculous number of selfies in one sitting?",
  "If you had to eat one food for every meal for a week, what would it be?",
  "What color best represents your personality?",
  "What’s your most used GIF or reaction image?",
  "If you had a fan club, what would they be called?",
  "Do you ever give your belongings nicknames?",
  "What’s something you love that other people find odd?",
  "If your life were a video game, what would the cheat code do?",
  "Have you ever had a funny misunderstanding because of autocorrect?",
  "If you could add a holiday to the calendar, what would it celebrate?",
  "What’s your favorite way to procrastinate?",
  "What’s a food combination you secretly enjoy?",
  "Would you rather be able to change colors like a chameleon or glow in the dark?",
  "What’s your favorite “bad” movie that you enjoy anyway?",
  "Have you ever had a dream so strange you laughed about it all day?",
  "What’s the most creative costume you’ve ever worn or wanted to wear?",
  "If you could turn anything into chocolate, what would it be?",
  "What’s the silliest nickname you’ve ever been given?",
  "Have you ever tried to beat a world record, just for fun?",
  "What’s your go-to comfort TV show or movie?",
  "Do you sing in the shower or car?",
  "What’s something small that instantly makes your day better?",
  "What’s a quirky tradition you have with your friends or family?",
  "What would your dream treehouse include?",
  "Would you rather be a famous comedian or a legendary prankster?",
  "If you had a personal mascot, what would it be?",
  "What’s a word you just love to say out loud?",
  "What would be your ideal pajama day activity?",
  "Have you ever laughed at the worst possible moment?",
  "What’s your favorite kind of weather for doing nothing?",
  "If you could float like a balloon for a day, where would you go?",
  "What’s a song lyric you always get wrong, but confidently sing anyway?",
  "Would you rather have roller skates for feet or springs for legs?",
  "Have you ever pretended to understand something when you didn’t?",
  "What’s the most embarrassing typo you’ve ever sent?",
  "What fictional world would you vacation in?",
  "What was your favorite recess game as a kid?",
  "Do you believe cereal is soup?",
  "What’s the most unnecessary but delightful thing you own?",
  "Would you rather live in a tiny house or a treehouse?",
  "Have you ever started laughing and couldn’t stop?",
  "What’s the oddest compliment you’ve ever received?",
  "What’s your favorite way to waste time online?",
  "If animals could talk, which one would be the sassiest?",
  "What sound always makes you smile?",
  "What’s your dream party theme?",
  "What flavor of ice cream best represents your mood today?",
  "What’s a fashion trend you secretly like?",
  "Do you believe in lucky socks or good luck charms?",
  "What’s a small misadventure that still makes you chuckle?",
  "If you could rename one everyday object, what would it be?",
  "What’s the goofiest thing you’ve ever done in public?",
  "What’s your spirit meme?",
  "What’s your ideal “lazy afternoon” scenario?",
  "Do you collect anything strange or nostalgic?",
  "If you had a magic vending machine, what would it dispense?",
  "What’s your favorite sound effect or silly noise?",
  "Have you ever gotten the giggles at a serious moment?",
  "What’s a toy you wish you still had?",
  "What snack do you always want at the movies?",
  "Would you rather time travel only to birthdays or only to vacations?",
  "What fictional character would make the best roommate?",
  "What board game brings out your competitive side?",
  "What’s the most fun you’ve ever had by accident?",
  "If you had your own festival, what would it celebrate?",
  "What’s a silly habit you have that makes you happy?",
  "Do you secretly enjoy bad weather?",
  "What’s something you always do “just for fun,” even if it’s silly?",
  "What’s the weirdest dream job you can think of?",
  "If you had a secret handshake, what would it include?",
  "What’s your favorite silly holiday (real or made-up)?",
  "Do you enjoy people-watching and making up their stories?",
  "What’s a movie you wish had a sequel?",
  "Have you ever made up your own word?",
  "Would you rather have a rewind or fast-forward button for awkward moments?",
  "If you could invent a new emoji, what would it look like?",
  "What’s a fun lie you believed for way too long?",
  "If you had to wear one costume for a week, what would it be?",
  "What’s your most memorable childhood adventure?",
  "What flavor combo should be illegal—but you kind of love it?",
  "If your laugh had a shape, what would it be?",
  "What’s your favorite game to play with friends?",
  "Would you rather have balloons or confetti follow you everywhere?",
  "If your pet could text, what would they say to you?",
  "What’s your favorite silly tradition or superstition?",
  "Have you ever had an accidental fashion moment?",
  "If you were a dessert, what dessert would you be?",
  "What’s your favorite sound of happiness?",
  "Have you ever tried to prank someone and failed?",
  "What would your “just for fun” museum exhibit be?",
  "If you could float in space for a day, what would you bring?",
  "What cartoon theme song still lives rent-free in your head?",
  "Would you rather be able to speak all animal languages or all fictional languages?",
  "What’s your dream toy invention?",
  "What’s your favorite childhood mispronunciation?",
  "If you had your own parade float, what would it look like?",
  "What’s your favorite ridiculous invention that actually exists?",
  "If you had to live in a theme park, which one would it be?",
  "Do you believe food tastes better when it’s stolen (from a friend’s plate)?",
  "What’s something super ordinary that brings you joy?",
  "What would be the silliest world record to attempt?",
  "If your dreams had a soundtrack, what kind of music would play?",
  "What’s the funniest thing a child has ever said to you?",
  "Would you rather always talk in rhymes or sing everything?",
  "What’s the best spontaneous idea you’ve ever had?",
  "What magical creature do you wish existed in real life?",
  "What would your dream treehouse or fort include?",
  "What’s your ultimate “treat yourself” plan?",
  "What’s something you do just to make others laugh?",
  "What animal do you think secretly runs the world?",
  "Have you ever gotten lost but had fun anyway?",
  "What’s your ultimate comfort outfit?",
  "What’s a scent that always brings back fun memories?",
  "What’s a talent you have that’s completely useless but fun?",
  "What would your “just for laughs” comedy skit be about?",
  "What’s the weirdest thing you’ve done on a dare?",
  "Would you rather ride a unicycle everywhere or hop like a bunny?",
  "What would be your dream job if money didn’t matter at all?",
  "What’s something silly you believed about adults as a kid?",
  "What’s a “just because” gift that made you smile?",
  "If you could make a rule everyone had to follow for a day, what would it be?",
  "What’s the most ridiculous autocorrect fail you’ve seen?",
  "What’s the best silly face you can make?",
  "What’s a word you always mispronounced as a kid?",
  "Have you ever named something totally random, like a pencil or a plant?",
  "What’s the funniest outfit you’ve ever worn on purpose?",
  "If you had a reality show, what would it be called?",
  "What’s something you do when you’re bored that always cheers you up?",
  "Have you ever sent a message to the wrong person—with hilarious results?",
  "What’s a smell you secretly love even though most people don’t?",
  "What song instantly makes you want to dance like nobody's watching?",
  "If you had a magical snack machine, what would be in it?",
  "Would you rather wear clown shoes for a year or oversized sunglasses?",
  "What’s a word you love just because it sounds funny?",
  "If you could live in a board game, which one would you choose?",
  "What’s the best prank you’ve ever seen or pulled?",
  "What’s your favorite thing to build out of LEGO or blocks?",
  "Would you rather bounce everywhere or slide everywhere?",
  "What’s your dream pajama party setup?",
  "What’s the most unexpected place you’ve found something fun?",
  "What do you wish was socially acceptable but totally isn’t?",
  "What’s a movie scene you wish you could jump into?",
  "What’s a food that instantly feels like a hug?",
  "What’s your go-to “silly voice”?",
  "Would you rather sneeze confetti or burp bubbles?",
  "What’s the best icebreaker question you’ve ever heard?",
  "What’s your favorite fictional pet or sidekick?",
  "What snack should be available in every vending machine?",
  "What’s the most fun form of transportation you’ve tried or want to try?",
  "What’s the funniest reason you’ve ever been late?",
  "What’s your ultimate game night snack?",
  "What fictional sport would you try if it were real?",
  "What’s something ridiculous that you love a little too much?",
  "What’s a silly quote you always remember?",
  "What’s your favorite tongue twister?",
  "If you could be a fly on the wall anywhere, where would you go?",
  "What’s a joke you always mess up but tell anyway?",
  "What would your dream treehouse fort be made of?",
  "Would you rather have googly eyes or squeaky shoes forever?",
  "What’s the strangest thing you’ve ever eaten (and liked)?",
  "What’s a fun tradition you’d love to start?",
  "What’s the best spontaneous photo you’ve ever taken?",
  "What’s your dream “do nothing” day?",
  "What’s your favorite unexpected flavor combo?",
  "What’s the best excuse you’ve ever heard (or used)?",
  "What’s something you laugh at every time, no matter what?",
  "What’s your ultimate “fun playlist” song?",
  "What would you do if gravity stopped for 10 seconds?",
  "What’s something so bad it’s good?",
  "What’s a fact that makes you giggle?",
  "What would your dream pillow fort look like?",
  "What’s a fictional creature you wish you could adopt?",
  "What was your most epic snow day or school holiday?",
  "What’s the most fun rule you’ve ever made up?",
  "What’s your favorite made-up holiday idea?",
  "What’s a dance move you secretly love?",
  "What’s a super silly fear you have?",
  "What’s a flavor you wish existed?",
  "What’s a time you couldn’t stop laughing?",
  "What’s a gift you once gave that made someone laugh?",
  "What’s a silly superstition you kind of follow?",
  "What’s your ultimate comfort food combo?",
  "What’s the most fun surprise you’ve ever had?",
  "What’s something you did as a kid that still makes you proud?",
  "What’s your favorite playful way to spend time?",
  "What’s the funniest misunderstanding you’ve been part of?",
  "What’s your go-to outfit when you want to feel cozy and fun?",
  "What’s a moment you wish you had on video forever?",
  "What’s your favorite silly thing to draw or doodle?",
  "What’s a fun sound you love?",
  "What’s something “useless” you’ve memorized for fun?",
  "What’s your favorite moment in a cartoon?",
  "What would your ultimate indoor playground have?",
  "What’s a word you love saying with extra flair?",
  "What’s something only your closest friend understands about your humor?",
  "What’s a voice impression you love doing?",
  "What’s a fantasy job that would be ridiculous but fun?",
  "What’s something quirky that instantly makes you smile?",
  "What’s a color combo you love even if it’s “weird”?",
  "What’s a sound you make when you're excited?",
  "What’s your ideal silly adventure?",
  "What’s your go-to happy dance move?",
  "What’s something small and ridiculous that you collect or save?",
  "What’s a word you like to shout dramatically for no reason?",
  "What’s a story you love telling because it’s just so funny?",
  "What’s your favorite made-up nickname?",
  "What’s something playful you did recently?",
  "What’s the funniest video you’ve watched lately?",
  "What’s a joke you know by heart?",
  "What would be in your “fun survival kit”?",
  "What’s your ideal silly group activity?",
  "What’s a fun “what if” scenario you love imagining?",
  "What’s the weirdest compliment you’ve ever given?",
  "What’s something fun you still do, even as an adult?",
  "What’s a goofy game you’d love everyone to play?",
  "What’s the funniest face you can make right now?",
  "What’s something that makes you laugh every time?",
  "What’s the most fun you’ve ever had by being completely yourself?",
  "What do you usually do during your lunch break?"
];