const questionsPart3 = [
  "What’s a good way to express disagreement without offending someone?",
  "How can you ask for help when you feel shy?",
  "What’s a gentle way to give constructive feedback?",
  "How do you explain your feelings clearly when upset?",
  "What’s a polite way to interrupt someone during a conversation?",
  "How can you express appreciation sincerely?",
  "How do you say you need time to think before answering?",
  "What’s a respectful way to disagree in a meeting?",
  "How do you express boundaries with friends?",
  "How can you refuse a gift politely?",
  "What’s a kind way to ask someone to repeat themselves?",
  "How do you express excitement without sounding over the top?",
  "What’s a tactful way to decline a favor?",
  "How can you express that you’re busy without seeming rude?",
  "How do you say “I don’t know” confidently?",
  "What’s a good way to ask for clarification?",
  "How do you express sympathy in a conversation?",
  "How can you admit a mistake gracefully?",
  "What’s a polite way to ask for more time on a task?",
  "How do you express disagreement with a family member?",
  "What’s a gentle way to tell someone their behavior bothers you?",
  "How can you say no to a coworker without damaging the relationship?",
  "How do you express that you need help without feeling weak?",
  "What’s a polite way to ask for someone’s opinion?",
  "How do you say you’re uncomfortable with a topic?",
  "How can you express interest in learning more about someone?",
  "What’s a respectful way to change the subject?",
  "How do you express disagreement during a debate?",
  "What’s a good way to thank someone for their support?",
  "How can you express frustration without sounding angry?",
  "How do you politely decline extra work?",
  "What’s a gentle way to remind someone of a deadline?",
  "How can you express enthusiasm at work?",
  "How do you give compliments that feel genuine?",
  "What’s a polite way to ask for quiet in a noisy place?",
  "How do you express concern without sounding critical?",
  "How can you say you don’t want to discuss something?",
  "What’s a good way to express your opinion in a group?",
  "How do you handle sarcasm when you don’t like it?",
  "How can you express disagreement with your boss?",
  "What’s a polite way to ask for feedback?",
  "How do you express that you feel left out?",
  "How can you say you’re sorry without over-apologizing?",
  "What’s a gentle way to ask someone to slow down when speaking?",
  "How do you express gratitude in a professional email?",
  "How can you say no to a salesperson politely?",
  "What’s a respectful way to ask for a raise?",
  "How do you express nervousness in a conversation?",
  "How can you give negative feedback constructively?",
  "What’s a polite way to ask someone to stop doing something?",
  "How do you express excitement about a new opportunity?",
  "How can you admit you don’t understand something?",
  "What’s a gentle way to end a conversation?",
  "How do you express your needs clearly in a relationship?",
  "How can you say no to a friend without hurting their feelings?",
  "What’s a good way to ask for advice?",
  "How do you express disagreement without escalating conflict?",
  "How can you compliment someone’s work professionally?",
  "What’s a polite way to ask for directions?",
  "How do you express surprise in a conversation?",
  "How can you say you’re busy without seeming uninterested?",
  "What’s a respectful way to express different political views?",
  "How do you ask for permission politely?",
  "How can you express disappointment without blaming?",
  "What’s a good way to express curiosity about a sensitive topic?",
  "How do you politely decline a dinner invitation?",
  "How can you express support to someone going through a tough time?",
  "What’s a gentle way to correct someone’s mistake?",
  "How do you say you don’t want to argue?",
  "How can you ask someone to be more clear?",
  "What’s a polite way to express disagreement in a group chat?",
  "How do you express appreciation for small gestures?",
  "How can you ask for more details about a project?",
  "What’s a good way to say you’re unsure about something?",
  "How do you express concern about a friend’s decision?",
  "How can you ask for quiet during a phone call?",
  "What’s a respectful way to ask someone to change a behavior?",
  "How do you say you need a break without offending?",
  "How can you express enthusiasm without overwhelming others?",
  "What’s a gentle way to say you disagree with a joke?",
  "How do you politely ask someone to speak slower?",
  "How can you say no to social events without feeling guilty?",
  "What’s a good way to express interest in someone’s culture?",
  "How do you express excitement about a team’s success?",
  "How can you ask for help when you feel embarrassed?",
  "What’s a polite way to disagree on social media?",
  "How do you express that you don’t want to share personal details?",
  "How can you ask someone to repeat important information?",
  "What’s a respectful way to handle criticism?",
  "How do you express frustration without being rude?",
  "How can you say you’re overwhelmed politely?",
  "What’s a good way to express hope for the future?",
  "How do you politely change your mind after agreeing?",
  "How can you ask for confirmation politely?",
  "What’s a gentle way to refuse help you don’t need?",
  "How do you express your point of view clearly?",
  "How can you ask someone to respect your privacy?",
  "What’s a polite way to refuse an offer of food or drink?",
  "How do you express encouragement to a shy speaker?",
  "How can you express disagreement without hurting feelings?",
  "What’s a kind way to ask for someone’s opinion when they’re quiet?",
  "How do you say you need to reschedule plans politely?",
  "How can you express gratitude in a handwritten note?",
  "What’s a polite way to express dissatisfaction with a service?",
  "How do you say no to extra work without seeming lazy?",
  "How can you express excitement about meeting new people?",
  "What’s a gentle way to correct someone’s pronunciation?",
  "How do you express your boundaries clearly in the workplace?",
  "How can you refuse a request from a close friend tactfully?",
  "What’s a polite way to ask for clarification on confusing instructions?",
  "How do you express empathy during a difficult conversation?",
  "How can you admit when you don’t have all the answers?",
  "What’s a respectful way to disagree with your partner?",
  "How do you politely ask someone to lower their voice?",
  "How can you express enthusiasm without interrupting others?",
  "What’s a good way to thank a colleague for their support?",
  "How do you ask for feedback after a presentation?",
  "How can you say no to a sales pitch politely?",
  "What’s a gentle way to let someone know their joke was offensive?",
  "How do you express appreciation for cultural differences?",
  "How can you ask for help when you don’t want to bother anyone?",
  "What’s a polite way to decline an invitation to a large event?",
  "How do you express frustration at work without losing professionalism?",
  "How can you ask for a deadline extension gracefully?",
  "What’s a good way to offer help without being intrusive?",
  "How do you express disappointment without blaming others?",
  "How can you say you’re not interested in a romantic way?",
  "What’s a respectful way to address a misunderstanding?",
  "How do you politely disagree with a popular opinion?",
  "How can you express that you feel overwhelmed at work?",
  "What’s a kind way to ask someone to repeat their name?",
  "How do you express excitement about learning something new?",
  "How can you say no to a networking event politely?",
  "What’s a gentle way to suggest an alternative idea?",
  "How do you express gratitude after receiving criticism?",
  "How can you ask for privacy without offending?",
  "What’s a polite way to ask for someone’s time?",
  "How do you express that you need to focus without seeming rude?",
  "How can you admit when you’re wrong in a debate?",
  "What’s a respectful way to ask for honesty?",
  "How do you say no to repeated requests without hurting feelings?",
  "How can you express nervousness in a confident way?",
  "What’s a good way to accept a compliment gracefully?",
  "How do you ask for help when you’re struggling with a task?",
  "How can you politely disagree in a text message?",
  "What’s a gentle way to set limits on social media interactions?",
  "How do you express excitement without sounding boastful?",
  "How can you say no to volunteering politely?",
  "What’s a respectful way to ask for changes in a group project?",
  "How do you express disappointment in a polite way?",
  "How can you ask for silence during a meeting?",
  "What’s a kind way to ask someone to clarify their feelings?",
  "How do you express that you don’t want to talk about a topic?",
  "How can you say no to a date without hurting feelings?",
  "What’s a polite way to give negative feedback?",
  "How do you express appreciation for small favors?",
  "How can you politely ask someone to be on time?",
  "What’s a gentle way to remind someone of an appointment?",
  "How do you say you’re unsure without seeming indecisive?",
  "How can you express disagreement without sounding confrontational?",
  "What’s a polite way to end a phone call?",
  "How do you express support to someone who is struggling?",
  "How can you ask for more information without sounding demanding?",
  "What’s a kind way to encourage someone who lacks confidence?",
  "How do you express your opinion when others disagree?",
  "How can you say no to a gift without offending?",
  "What’s a polite way to decline an offer for food or drink?",
  "How do you express that you need time alone?",
  "How can you admit you need to improve without losing confidence?",
  "What’s a gentle way to tell someone their behavior is inappropriate?",
  "How do you express gratitude for someone’s patience?",
  "How can you say no to a favor politely?",
  "What’s a respectful way to ask someone to stop talking?",
  "How do you express excitement in a professional setting?",
  "How can you ask for a second chance respectfully?",
  "What’s a polite way to ask for a meeting reschedule?",
  "How do you express your limits with family members?",
  "How can you say no to extra responsibilities at work?",
  "What’s a gentle way to ask someone to lower their music?",
  "How do you express that you’re proud of your achievements?",
  "How can you politely ask for someone’s attention?",
  "What’s a respectful way to disagree in a public discussion?",
  "How do you express curiosity without being intrusive?",
  "How can you say no to a social invitation politely?",
  "What’s a kind way to express that you’re feeling stressed?",
  "How do you ask for help when you’re afraid to seem weak?",
  "How can you express excitement about future plans?",
  "What’s a polite way to decline attending a party?",
  "How do you express disagreement without offending your boss?",
  "How can you say no to a request from a family member?",
  "What’s a gentle way to express your feelings about a sensitive topic?",
  "How do you express thanks after receiving a compliment?",
  "How can you politely ask for someone’s opinion?",
  "What’s a respectful way to ask for time to think?",
  "How do you express that you need to leave a conversation early?",
  "How can you say no to a group activity without guilt?",
  "What’s a kind way to ask someone to explain their point?",
  "How do you express frustration without blaming others?",
  "How can you politely correct someone’s misunderstanding?",
  "What’s a gentle way to suggest a change of plans?",
  "How do you express disagreement in a text message?",
  "How can you ask for feedback on your work?",
  "What’s a respectful way to disagree with a friend?",
  "How do you express gratitude to a mentor?",
  "How can you say no to a colleague’s request politely?",
  "What’s a polite way to ask for quiet in a public place?",
  "How do you express excitement about a promotion?",
  "How can you ask for advice without seeming unsure?",
  "What’s a gentle way to refuse an invitation?",
  "How do you express that you’re overwhelmed without sounding negative?",
  "How can you politely ask someone to respect your boundaries?",
  "What’s a kind way to express your disagreement?",
  "How do you express appreciation for teamwork?",
  "How can you say no to a favor from a stranger?",
  "What’s a polite way to request clarification?",
  "How do you express your feelings about a difficult decision?",
  "How can you ask for help when you don’t want to bother anyone?",
  "What’s a gentle way to say you’re tired?",
  "How do you express encouragement to a friend?",
  "How can you say no to extra tasks without offending?",
  "What’s a polite way to ask for an extension on a deadline?",
  "How do you express concern without sounding critical?",
  "How can you politely decline a date?",
  "What’s a respectful way to express your needs?",
  "How do you express excitement about a new hobby?",
  "How can you say no to a colleague’s lunch invitation?",
  "What’s a gentle way to remind someone of their responsibilities?",
  "How do you express gratitude in a professional email?",
  "How can you ask for help with a project?",
  "What’s a polite way to decline a gift?",
  "How do you express disagreement with your manager?",
  "How can you say no to a request from a friend?",
  "What’s a kind way to express your feelings honestly?",
  "How do you express excitement without sounding boastful?",
  "How can you politely ask for more information?",
  "What’s a gentle way to say you don’t understand?",
  "How do you express appreciation for someone’s effort?",
  "How can you ask for feedback after a meeting?",
  "What’s a polite way to refuse a favor?",
  "How do you express that you need a break?",
  "How can you say no to social invitations politely?",
  "What’s a kind way to express disagreement in a group?",
  "How do you express gratitude for emotional support?",
  "How can you politely ask someone to speak slower?",
  "What’s a gentle way to decline attending an event?",
  "How do you express excitement about a team achievement?",
  "How can you say no to volunteering without offending?",
  "What’s a respectful way to give negative feedback?",
  "How do you express your limits clearly?",
  "How can you politely refuse an offer?",
  "What’s a kind way to ask for clarification during a discussion?",
  "How do you express your feelings during a disagreement?",
  "How can you say no without feeling guilty?",
  "What’s a polite way to ask for help at work?",
  "How do you express appreciation after receiving help?",
  "How can you politely decline a business proposal?",
  "What’s a gentle way to ask someone to be patient?",
  "How do you express frustration without escalating conflict?",
  "How can you say no to a request without offending?",
  "What’s a kind way to express your opinions in a debate?",
  "How do you express gratitude in difficult situations?",
  "How can you politely ask for time to respond?",
  "What’s a respectful way to disagree in a discussion?",
  "How do you express excitement about personal growth?",
  "How can you say no to unwanted advice?",
  "What’s a gentle way to express discomfort?",
  "How do you express your boundaries at social events?",
  "How can you politely ask someone to lower their voice?",
  "What’s a kind way to express disagreement with a joke?",
  "How do you express enthusiasm for a new project?",
  "How can you say no to additional work respectfully?",
  "What’s a polite way to ask for a second opinion?",
  "How do you express concern for a friend’s well-being?",
  "How can you politely decline an invitation to travel?",
  "What’s a gentle way to ask someone to respect your time?",
  "How do you express gratitude to a teacher or coach?",
  "How can you say no to a family request without guilt?",
  "What’s a kind way to express your feelings about a mistake?",
  "How do you express excitement without overwhelming others?",
  "How can you politely ask for assistance?",
  "What’s a respectful way to express different beliefs?",
  "How do you express your feelings in a professional setting?",
  "How can you say no to social gatherings politely?",
  "What’s a gentle way to refuse help you don’t need?",
  "How do you express appreciation for a mentor?",
  "How can you politely ask someone to be more clear?",
  "What’s a kind way to express disagreement in a team?",
  "How do you express excitement about a personal achievement?",
  "How can you say no to extra responsibilities without offending?",
  "What’s a polite way to request feedback on a presentation?",
  "How do you express concern about a coworker’s behavior?",
  "How can you politely decline a favor from a colleague?",
  "What’s a gentle way to say you’re not interested?",
  "How do you express gratitude for a thoughtful gesture?",
  "How can you say no to social media requests politely?",
  "What’s a respectful way to express your needs in a relationship?",
  "How do you express enthusiasm about a group project?",
  "How can you politely ask for clarification in a conversation?",
  "What’s a kind way to express disagreement without conflict?",
  "How do you express frustration without sounding angry?",
  "What’s a polite way to refuse an unexpected visitor?",
  "How can you say no to a persistent salesperson?",
  "What’s a kind way to express that you need personal space?",
  "How do you politely ask someone to stop interrupting?",
  "How can you express appreciation in a team meeting?",
  "What’s a gentle way to let someone know they’re speaking too fast?",
  "How do you express that you don’t want to discuss politics?",
  "How can you say no to joining a committee politely?",
  "What’s a respectful way to ask for honest feedback?",
  "How do you express excitement for a friend’s success?",
  "How can you politely decline a lunch invitation?",
  "What’s a kind way to ask for more time to complete a task?",
  "How do you express disagreement without offending family members?",
  "How can you say no to a colleague’s request without guilt?",
  "What’s a polite way to express that you’re overwhelmed?",
  "How do you express gratitude for unexpected help?",
  "How can you gently refuse an invitation to a party?",
  "What’s a respectful way to express different cultural views?",
  "How do you express your limits in a professional relationship?",
  "How can you say no to a project without damaging relationships?",
  "What’s a kind way to ask for clarification on sensitive topics?",
  "How do you express disappointment constructively?",
  "How can you politely ask someone to respect your time?",
  "What’s a gentle way to suggest a better solution?",
  "How do you express gratitude to a difficult colleague?",
  "How can you say no to social obligations politely?",
  "What’s a respectful way to disagree in a public forum?",
  "How do you express concern about a friend’s health?",
  "How can you politely decline a gift you don’t want?",
  "What’s a kind way to express disagreement on social media?",
  "How do you express excitement about learning new skills?",
  "How can you say no to additional responsibilities at home?",
  "What’s a polite way to ask someone to lower their volume?",
  "How do you express gratitude after a difficult conversation?",
  "How can you gently refuse a business proposal?",
  "What’s a respectful way to express your opinion in a meeting?",
  "How do you say no to a networking event without offending?",
  "How can you express frustration with a service professionally?",
  "What’s a kind way to ask someone to repeat important information?",
  "How do you express excitement about a new opportunity?",
  "How can you politely refuse to share personal information?",
  "What’s a respectful way to express disagreement with a teacher?",
  "How do you express gratitude for mentorship?",
  "How can you say no to a friend’s request without feeling guilty?",
  "What’s a gentle way to express your feelings about a difficult subject?",
  "How do you politely ask for time to think over a decision?",
  "How can you express your boundaries clearly in friendships?",
  "What’s a kind way to encourage someone who is shy?",
  "How do you express excitement about a team achievement?",
  "How can you say no to volunteering for extra work?",
  "What’s a polite way to ask for feedback after a presentation?",
  "How do you express concern without sounding critical?",
  "How can you politely decline a date invitation?",
  "What’s a respectful way to express your needs in a relationship?",
  "How do you express excitement about a personal goal?",
  "How can you say no to a coworker’s lunch invitation?",
  "What’s a gentle way to remind someone of a deadline?",
  "How do you express gratitude professionally in an email?",
  "How can you ask for help without seeming weak?",
  "What’s a polite way to refuse an unexpected favor?",
  "How do you express disagreement respectfully in a team?",
  "How can you say no to a social media request politely?",
  "What’s a kind way to express your opinion in a group chat?",
  "How do you express excitement about a new hobby?",
  "How can you politely ask for more information?",
  "What’s a gentle way to say you don’t understand a concept?",
  "How do you express appreciation for a colleague’s work?",
  "How can you ask for feedback after a project?",
  "What’s a polite way to refuse a favor?",
  "How do you express that you need a break from social media?",
  "How can you say no to social events without feeling guilty?",
  "What’s a kind way to express disagreement without conflict?",
  "How do you express gratitude for emotional support?",
  "How can you politely ask someone to speak slower?",
  "What’s a gentle way to decline attending an event?",
  "How do you express excitement about a team’s success?",
  "How can you say no to volunteering without offending?",
  "What’s a respectful way to give negative feedback?",
  "How do you express your limits clearly to others?",
  "How can you politely refuse an offer?",
  "What’s a kind way to ask for clarification during a discussion?",
  "How do you express your feelings during a disagreement?",
  "How can you say no without feeling guilty?",
  "What’s a polite way to ask for help at work?",
  "How do you express appreciation after receiving help?",
  "How can you politely decline a business proposal?",
  "What’s a gentle way to ask someone to be patient?",
  "How do you express frustration without escalating conflict?",
  "How can you say no to a request without offending?",
  "What’s a kind way to express your opinions in a debate?",
  "How do you express gratitude in difficult situations?",
  "How can you politely ask for time to respond?",
  "What’s a respectful way to disagree in a discussion?",
  "How do you express excitement about personal growth?",
  "How can you say no to unwanted advice?",
  "What’s a gentle way to express discomfort?",
  "How do you express your boundaries at social events?",
  "How can you politely ask someone to lower their voice?",
  "What’s a kind way to express disagreement with a joke?",
  "How do you express enthusiasm for a new project?",
  "How can you say no to additional work respectfully?",
  "What’s a polite way to ask for a second opinion?",
  "How do you express concern for a friend’s well-being?",
  "How can you politely decline an invitation to travel?",
  "What’s a gentle way to ask someone to respect your time?",
  "How do you express gratitude to a teacher or coach?",
  "How can you say no to a family request without guilt?",
  "What’s a kind way to express your feelings about a mistake?",
  "How do you express excitement without overwhelming others?",
  "How can you politely ask for assistance?",
  "What’s a respectful way to express different beliefs?",
  "How do you express your feelings in a professional setting?",
  "How can you say no to social gatherings politely?",
  "What’s a gentle way to refuse help you don’t need?",
  "How do you express appreciation for a mentor?",
  "How can you politely ask someone to be more clear?",
  "What’s a kind way to express disagreement in a team?",
  "How do you express excitement about a personal achievement?",
  "How can you say no to extra responsibilities without offending?",
  "What’s a polite way to request feedback on a presentation?",
  "How do you express concern about a coworker’s behavior?",
  "How can you politely decline a favor from a colleague?",
  "What’s a gentle way to say you’re not interested?",
  "How do you express gratitude for a thoughtful gesture?",
  "How can you say no to social media requests politely?",
  "What’s a respectful way to express your needs in a relationship?",
  "How do you express enthusiasm about a group project?",
  "How can you politely ask for clarification in a conversation?",
  "What’s a kind way to express disagreement without conflict?",
  "How do you express excitement about an upcoming event?",
  "How can you say no to an invitation without offending?",
  "What’s a polite way to ask for someone’s opinion?",
  "How do you express appreciation for teamwork?",
  "How can you politely decline extra work from a supervisor?",
  "What’s a gentle way to ask for help when feeling overwhelmed?",
  "How do you express disagreement during a group discussion?",
  "How can you say no to a last-minute request politely?",
  "What’s a respectful way to express your feelings about a sensitive topic?",
  "How do you express gratitude to a friend who supports you?",
  "How can you politely ask for someone to lower their tone?",
  "What’s a kind way to express disagreement with a family member?",
  "How do you express excitement about a new challenge?",
  "How can you say no to a social event without hurting feelings?",
  "What’s a polite way to ask for feedback on your performance?",
  "How do you express appreciation in a thank-you note?",
  "How can you politely decline a request for a loan?",
  "What’s a gentle way to remind someone about a commitment?",
  "How do you express your feelings about a change in plans?",
  "How can you say no to a favor without feeling guilty?",
  "What’s a respectful way to express your opinion in a debate?",
  "How do you express excitement about a vacation?",
  "How can you politely ask for help with a difficult task?",
  "What’s a kind way to express disagreement with a colleague?",
  "How do you express gratitude for a compliment?",
  "How can you say no to a sales offer politely?",
  "What’s a gentle way to refuse an offer you don’t want?",
  "How do you express your boundaries in a new relationship?",
  "How can you politely ask someone to respect your decisions?",
  "What’s a respectful way to express disagreement with a teacher?",
  "How do you express excitement about learning a new skill?",
  "How can you say no to additional work assignments?",
  "What’s a polite way to ask for clarification on a contract?",
  "How do you express gratitude after a job interview?",
  "How can you politely decline a social media friend request?",
  "What’s a kind way to express disagreement during a meeting?",
  "How do you express your feelings about a difficult conversation?",
  "How can you say no to an invitation to join a club?",
  "What’s a gentle way to express that you need help?",
  "How do you express excitement about a new relationship?",
  "How can you politely ask for time to consider an offer?",
  "What’s a respectful way to express your opinion in a survey?",
  "How do you express gratitude for a helpful colleague?",
  "How can you say no to a charity request politely?",
  "What’s a kind way to express disagreement on a project?",
  "How do you express your feelings after receiving criticism?",
  "How can you politely decline an invitation to a wedding?",
  "What’s a gentle way to ask someone to stop a behavior?",
  "How do you express excitement about a promotion?",
  "How can you say no to extra duties at school?",
  "What’s a polite way to ask for feedback on writing?",
  "How do you express gratitude for a teacher’s guidance?",
  "How can you politely refuse an invitation to dinner?",
  "What’s a kind way to express disagreement in a friendship?",
  "How do you express your feelings about a family gathering?",
  "How can you say no to a request for a favor politely?",
  "What’s a respectful way to express your boundaries at work?",
  "How do you express excitement about a new project?",
  "How can you politely ask for a deadline extension?",
  "What’s a gentle way to decline a request for a loan?",
  "How do you express gratitude for emotional support?",
  "How can you say no to social invitations without offending?",
  "What’s a kind way to express disagreement during a conversation?",
  "How do you express your feelings about a difficult decision?",
  "How can you politely ask for clarification on instructions?",
  "What’s a respectful way to express your opinion on politics?",
  "How do you express excitement about travel plans?",
  "How can you say no to a last-minute invitation?",
  "What’s a polite way to ask for help during a crisis?",
  "How do you express gratitude for kindness shown to you?",
  "If you woke up one day with a superpower, what would it be and why?"
];