const questionsPart5 = [
  "How do you usually start your day?",
  "What’s your go-to drink when you’re tired?",
  "How do you keep track of your schedule?",
  "What’s one thing you always bring when you leave the house?",
  "Do you prefer taking notes by hand or digitally?",
  "What helps you fall asleep more easily?",
  "What’s your cleaning routine like?",
  "How do you stay organized at home?",
  "What kind of bag do you carry daily?",
  "Do you prefer working in silence or with background noise?",
  "How do you manage your monthly budget?",
  "What’s your favorite way to exercise or move your body?",
  "Do you plan your meals or decide on the spot?",
  "What’s one small daily habit that makes your day better?",
  "How do you usually commute?",
  "What do you usually eat for lunch during the week?",
  "How do you keep your phone from distracting you?",
  "What’s your favorite app for productivity?",
  "What’s one errand you don’t mind doing?",
  "Do you usually cook or eat out for dinner?",
  "How do you like to unwind after a long day?",
  "Do you prefer mornings or evenings?",
  "What’s your laundry routine like?",
  "How do you prepare for a big day?",
  "What’s something you always keep in your fridge?",
  "What’s your favorite home appliance?",
  "What type of calendar system do you use, if any?",
  "Do you keep a to-do list? How?",
  "What’s your favorite snack?",
  "What helps you stay hydrated during the day?",
  "What do you usually do during your lunch break?",
  "How do you organize your digital files?",
  "What’s your preferred grocery shopping routine?",
  "What do you listen to during your commute?",
  "How do you keep track of tasks at work or school?",
  "What’s your favorite brand of everyday item (e.g., pen, mug, water bottle)?",
  "What’s your system for dealing with emails or messages?",
  "What’s your strategy for packing for a trip?",
  "What’s your approach to keeping your space tidy?",
  "What do you do when something breaks at home?",
  "How do you handle bad traffic or delays?",
  "What’s your go-to weekday dinner recipe?",
  "What’s your favorite way to spend a Sunday?",
  "How often do you check the news?",
  "What kind of shoes do you wear most often?",
  "Do you prefer physical books or e-books for reading?",
  "How do you track your health or fitness?",
  "What’s one way you save time in your daily routine?",
  "What’s one chore you enjoy more than others?",
  "How do you deal with unexpected schedule changes?",
  "What’s your favorite way to relax at home?",
  "What do you normally do on rainy days?",
  "Do you like having background music while doing chores?",
  "What’s your weekend routine like?",
  "How do you keep your clothes organized?",
  "What’s your go-to way to fix something simple?",
  "How do you remember important dates or events?",
  "What’s your usual bedtime?",
  "What helps you stay focused when working?",
  "How do you deal with too many notifications?",
  "What’s your routine for winding down before bed?",
  "Do you keep a regular sleep schedule?",
  "What’s your go-to item when you need to feel cozy?",
  "How do you organize your personal finances?",
  "What’s one small thing you do to treat yourself?",
  "How do you handle meal planning for the week?",
  "What’s your usual morning beverage?",
  "What’s your approach to buying clothes?",
  "How do you prepare for a rainy or cold day?",
  "What’s your favorite season and why?",
  "What do you usually wear when working from home?",
  "How do you get motivated on lazy days?",
  "What’s one item you always keep in your car or bag?",
  "What’s your daily skincare or grooming routine?",
  "What’s your most-used home item?",
  "What’s your favorite type of pen or writing tool?",
  "How do you make your home feel cozy?",
  "What’s one habit you’re working on building?",
  "How do you track your monthly expenses?",
  "What’s your approach to meal prepping?",
  "Do you like doing dishes by hand or using a dishwasher?",
  "How often do you reorganize your room or space?",
  "What kind of lighting do you like in your workspace?",
  "What’s your method for remembering passwords?",
  "What’s one item you’ve bought that improved daily life?",
  "What’s your favorite comfort food?",
  "How do you handle days when you’re short on time?",
  "What’s one part of your routine you want to improve?",
  "How do you clean your digital devices?",
  "What’s your favorite type of home fragrance (e.g., candles, incense)?",
  "What’s one app you use every day?",
  "What’s your way of tracking water intake?",
  "How do you choose what to wear in the morning?",
  "What’s your go-to breakfast on a busy day?",
  "How do you keep your desk or workspace organized?",
  "What’s your most-used kitchen item?",
  "What’s your favorite way to spend 10 minutes alone?",
  "What helps you reset during a stressful day?",
  "How do you handle being interrupted while working?",
  "How do you usually start your day?",
  "What’s your go-to breakfast?",
  "How do you organize your to-do list?",
  "What’s your favorite way to relax after work?",
  "How do you usually get to work or school?",
  "How often do you clean your room or house?",
  "What’s your favorite item in your home and why?",
  "What kind of music do you listen to while doing chores?",
  "What’s your method for remembering appointments?",
  "How do you plan your weekly grocery shopping?",
  "What’s your daily skincare or grooming routine?",
  "How do you keep track of your expenses?",
  "What’s something you always carry with you?",
  "What’s your favorite lunch when you're in a hurry?",
  "What do you usually wear on a lazy weekend?",
  "How often do you cook at home?",
  "How do you keep your energy up during a long day?",
  "What’s a small daily habit that improves your life?",
  "How do you prepare for an important day?",
  "How do you manage your digital files and emails?",
  "What’s your system for doing laundry?",
  "How do you handle unexpected delays or traffic?",
  "What app do you use most in daily life?",
  "How often do you exercise?",
  "What’s your bedtime routine?",
  "What’s your favorite weekday dinner?",
  "How do you unwind before going to sleep?",
  "What’s a practical item you recommend to everyone?",
  "How do you usually spend your lunch break?",
  "How do you deal with daily distractions?",
  "What’s your favorite way to commute?",
  "How do you manage your time on a busy day?",
  "How do you handle household repairs or problems?",
  "What’s your cleaning strategy for your home?",
  "What’s your favorite errand to run and why?",
  "What’s something you do every Sunday?",
  "What’s your favorite app for staying organized?",
  "What’s a healthy snack you enjoy?",
  "How do you prioritize your daily tasks?",
  "What’s one routine you can’t skip?",
  "How do you pack for a regular workday?",
  "What’s your favorite season for daily life?",
  "How do you usually stay hydrated throughout the day?",
  "What’s your least favorite chore and how do you deal with it?",
  "How do you stay updated with news or current events?",
  "What’s one thing you do every morning without fail?",
  "What helps you stay focused while working or studying?",
  "What’s your usual routine on a rainy day?",
  "What’s your best tip for staying productive?",
  "How do you manage your screen time?",
  "What’s your method for planning meals?",
  "How do you usually plan your weekends?",
  "What’s something you always forget to do until the last minute?",
  "What’s your go-to coffee or tea order?",
  "What’s your system for budgeting money?",
  "How do you remind yourself to drink enough water?",
  "What’s one everyday product you can’t live without?",
  "What’s your system for organizing your closet?",
  "How do you store important documents or receipts?",
  "How do you handle daily decision fatigue?",
  "What’s your favorite way to save time during the day?",
  "What’s your routine when you feel tired in the afternoon?",
  "How do you shop for clothes efficiently?",
  "How often do you check your phone in a day?",
  "What’s one thing you do every night before bed?",
  "What’s your favorite way to spend a Saturday morning?",
  "What’s your go-to method for dealing with small stressors?",
  "How do you maintain a clean and tidy space?",
  "What’s your most used household item?",
  "What’s your favorite tool or gadget at home?",
  "What’s your daily breakfast routine on weekdays vs weekends?",
  "How do you fit hobbies into your daily life?",
  "What’s your go-to method for staying on time?",
  "How do you plan for unexpected changes in your schedule?",
  "What helps you stay motivated throughout the week?",
  "How do you manage multiple commitments in a day?",
  "What’s your favorite way to meal prep?",
  "What’s your system for packing before a trip?",
  "What do you do when you run out of groceries?",
  "How do you plan your monthly expenses?",
  "How often do you check your calendar or planner?",
  "What’s your favorite way to treat yourself after a long day?",
  "What do you listen to while doing repetitive tasks?",
  "What’s something you’ve automated in your daily life?",
  "How do you stay active if you work a desk job?",
  "How do you keep your phone from distracting you?",
  "What’s your favorite daily ritual?",
  "How do you organize your kitchen?",
  "What’s your strategy for avoiding procrastination?",
  "What helps you stay consistent with good habits?",
  "What’s your favorite way to do weekly reflection or planning?",
  "How do you plan around appointments or social events?",
  "What’s your system for doing dishes?",
  "How do you manage daily life with family or roommates?",
  "What’s your most productive time of day?",
  "How do you track your health or fitness goals?",
  "What’s your routine when you’re feeling under the weather?",
  "How do you prepare for a rainy or bad weather day?",
  "How do you balance rest and responsibility each day?",
  "What’s your approach to daily self-care?",
  "How do you usually spend your weekends?",
  "What’s your go-to comfort food?",
  "How do you keep track of your schedule?",
  "What’s your favorite grocery store item?",
  "How do you unwind after a busy day?",
  "What’s your favorite thing to cook or eat at home?",
  "How do you manage your monthly expenses?",
  "What’s one chore you secretly enjoy?",
  "How do you usually wake yourself up in the morning?",
  "What’s your favorite way to stay active?",
  "How do you decide what to wear each day?",
  "What’s your usual breakfast routine?",
  "How do you deal with traffic or commuting stress?",
  "What’s a small daily habit that improves your mood?",
  "How do you stay hydrated throughout the day?",
  "What do you keep in your bag or backpack?",
  "How do you organize your workspace?",
  "What’s your favorite way to take notes or make to-do lists?",
  "What’s your most used phone app?",
  "How do you clean your living space efficiently?",
  "How do you prepare for the next day before bed?",
  "What’s something you always do before leaving the house?",
  "How do you manage your email or messages?",
  "What do you usually do during lunch breaks?",
  "How do you handle unexpected errands or interruptions?",
  "What’s your favorite weekday dinner?",
  "How do you stay informed about current events?",
  "What’s your favorite way to treat yourself after a tough day?",
  "How do you usually do your laundry?",
  "What’s your cleaning routine like?",
  "How do you handle last-minute schedule changes?",
  "What’s your favorite budget-friendly activity?",
  "How do you stay on top of your tasks?",
  "What’s your strategy for shopping smartly?",
  "What’s your typical morning routine on workdays?",
  "How do you pack for a short trip?",
  "What’s your daily skincare or grooming routine?",
  "How do you plan your meals for the week?",
  "What’s your go-to snack when you're in a rush?",
  "How do you avoid wasting food?",
  "What’s your method for remembering important dates?",
  "How do you plan your grocery list?",
  "How do you decide whether to cook or eat out?",
  "What’s your favorite way to relax on a Sunday?",
  "How do you keep your devices organized?",
  "What’s your system for handling receipts or paperwork?",
  "How do you manage household supplies?",
  "What’s something small that keeps your home feeling cozy?",
  "How do you store seasonal clothing?",
  "How do you keep your fridge or pantry organized?",
  "What’s your go-to method for waking up on time?",
  "How do you handle home maintenance tasks?",
  "What’s your preferred way to keep track of personal goals?",
  "How do you declutter your living space?",
  "What’s your strategy for remembering names or faces?",
  "How do you store digital files or documents?",
  "What’s your process for making big purchases?",
  "How do you check the weather before heading out?",
  "What’s your favorite household item and why?",
  "How do you manage screen time?",
  "What’s your secret to staying productive at home?",
  "How do you handle returning items you bought?",
  "What’s something you always keep in your fridge?",
  "How do you make cleaning feel less like a chore?",
  "What’s your routine before going to the gym or a workout?",
  "How do you keep your clothes in good shape?",
  "What’s your favorite small appliance or tool at home?",
  "How do you handle laundry emergencies?",
  "How do you deal with a cluttered inbox?",
  "What’s your backup plan when you forget something important?",
  "How do you keep your car or bike in good condition?",
  "How do you organize your digital calendar?",
  "What’s your method for staying motivated daily?",
  "How do you plan a quick, easy dinner?",
  "What’s a small thing that saves you time every day?",
  "How do you handle power outages or internet downtime?",
  "What’s your favorite home scent or candle?",
  "How do you manage multiple responsibilities at once?",
  "What’s your method for packing lunch?",
  "How do you keep your bedroom feeling restful?",
  "What’s your daily water drinking trick?",
  "How do you make sure you get enough sleep?",
  "How do you keep your shoes organized?",
  "What’s your favorite cleaning tool or product?",
  "How do you make time for hobbies in your routine?",
  "What’s your weekend grocery shopping tip?",
  "How do you make your space feel more like home?",
  "What’s something you always keep by your bed?",
  "How do you keep your bathroom tidy?",
  "What’s your method for backing up important data?",
  "How do you make cleaning up faster?",
  "What’s your morning hack for getting out the door quickly?",
  "How do you keep your energy up during the afternoon?",
  "What’s your favorite reusable item for daily use?",
  "How do you simplify your daily decisions?",
  "What’s a practical item you think everyone should have?",
  "How do you store or organize your chargers and cords?",
  "What’s your method for finding things you’ve misplaced?",
  "How do you keep your workspace comfortable?",
  "What’s a habit that keeps your mornings smooth?",
  "How do you rotate through outfits without repeating too much?",
  "What’s your trick for remembering errands?",
  "How do you deal with unexpected guests at home?",
  "What’s your favorite part of your daily routine?",
  "How do you keep your mind clear while doing chores?",
  "What’s your usual snack stash?",
  "How do you manage tasks when you’re overwhelmed?",
  "What’s your favorite way to carry essentials when going out?",
  "How do you prep for a productive Monday?",
  "What’s something that always lifts your mood at home?",
  "How do you handle multiple tabs or windows on your computer?",
  "What’s your ideal bedtime routine?",
  "How do you motivate yourself to do boring tasks?",
  "What’s a small detail that makes your day better?",
  "How do you streamline morning decisions like clothes and breakfast?",
  "What’s your trick for not forgetting reusable bags?",
  "How do you track small wins or successes?",
  "What’s your approach to keeping your phone organized?",
  "How do you prepare for unexpected weather?",
  "What’s a small thing you do that saves you money?",
  "How do you tidy up quickly before someone visits?",
  "What’s your secret for staying cool in hot weather?",
  "How do you plan for cleaning during a busy week?",
  "What’s something you do every Sunday?",
  "How do you avoid distractions at home?",
  "What’s your method for doing dishes efficiently?",
  "How do you get motivated to cook at home?",
  "What’s your favorite part of your workspace?",
  "How do you keep your pets’ space clean?",
  "What’s your trick for remembering small tasks?",
  "How do you balance screen time and rest?",
  "What’s your usual method for folding laundry?",
  "How do you prepare your home for visitors?",
  "What’s your strategy for shopping online?",
  "How do you manage tech or appliance repairs?",
  "What’s your best tip for a smooth morning commute?",
  "How do you handle household disagreements about chores?",
  "What’s something you do to refresh your space?",
  "How do you organize your kitchen tools?",
  "What’s your routine for a relaxing bath or shower?",
  "How do you store your seasonal decorations?",
  "What’s your favorite cleaning playlist or background noise?",
  "How do you prep your home before leaving for a trip?",
  "What’s your preferred cleaning schedule: daily, weekly, or monthly?",
  "How do you track things like bills or rent?",
  "What’s your go-to way to fix a bad mood?",
  "How do you keep your phone from being distracting?",
  "What’s your method for defrosting or prepping frozen food?",
  "How do you rotate clothes seasonally?",
  "What’s your secret for staying cozy at home?",
  "How do you clean up after a party or gathering?",
  "What’s your best tip for keeping your bathroom fresh?",
  "How do you deal with household maintenance emergencies?",
  "What’s your favorite low-effort home improvement trick?",
  "How do you label or store important papers?",
  "What’s a simple trick that helps your day go smoother?",
  "How do you schedule downtime during a busy week?",
  "What’s your method for keeping your freezer organized?",
  "How do you prep your space for deep cleaning?",
  "What’s your best advice for roommates or housemates?",
  "How do you adjust your routine when you’re sick?",
  "What’s your plan for handling dirty dishes during a busy day?",
  "How do you choose cleaning products?",
  "What’s a small home upgrade that made a big difference?",
  "How do you stay cool without air conditioning?",
  "What’s something that always improves your living space?",
  "How do you deal with clutter from mail or packages?",
  "What’s your favorite daily ritual?",
  "How do you balance comfort and productivity at home?",
  "What’s your go-to way to reset your space?",
  "How do you clean items that are hard to wash?",
  "What’s your trick for keeping shared spaces tidy?",
  "How do you reward yourself after chores?",
  "What’s something you like to keep within arm’s reach?",
  "How do you manage your grocery storage space?",
  "What’s your trick for saving water or energy?",
  "How do you handle something breaking at home?",
  "What’s your go-to solution for spills or messes?",
  "How do you manage routines with kids or pets?",
  "What’s a smell that makes your space feel clean?",
  "How do you split chores fairly?",
  "What’s your habit for remembering appointments?",
  "How do you clean without getting overwhelmed?",
  "What’s a practical hack you love using at home?",
  "How do you handle things piling up during a busy week?",
  "What’s your approach to cleaning under furniture?",
  "How do you manage your recycling or trash?",
  "What’s something you always keep in your car or bag?",
  "How do you prevent losing your keys or wallet?",
  "What’s your tip for staying on time in the morning?",
  "How do you simplify your meals when life gets busy?",
  "What’s a household item you use every day?",
  "How do you handle tech that stops working suddenly?",
  "What’s your trick for making your home feel peaceful?",
  "How do you rotate or replace basic household items?",
  "What’s your method for organizing under the sink?",
  "How do you clean or refresh your air indoors?",
  "What’s a smart way to use vertical space at home?",
  "How do you find motivation to clean when you’re tired?",
  "What’s your favorite part of daily life?",
  "What’s your go-to lunch on a busy day?",
  "How do you usually spend your Sunday afternoons?",
  "What’s something small you do to take care of your health?",
  "How do you plan your grocery shopping?",
  "What’s a household chore you secretly enjoy?",
  "How do you keep track of your daily to-do list?",
  "What helps you stay hydrated throughout the day?",
  "What’s your favorite way to treat yourself after a long week?",
  "What’s something you’ve recently learned to cook?",
  "How do you decide what clothes to wear each day?",
  "What’s one little routine that helps you feel grounded?",
  "How do you usually organize your workspace?",
  "What’s a practical tip you’d give someone living alone for the first time?",
  "How do you remember birthdays and important dates?",
  "What’s your favorite way to make a small space feel cozy?",
  "What do you do when your phone is running out of battery but you’re not home?",
  "How do you manage screen time on your devices?",
  "What’s one thing you always keep in your bag or backpack?",
  "How do you usually handle minor tech issues at home?",
  "What’s your system for cleaning or tidying up your room?",
  "How do you plan your meals for the week?",
  "What do you usually do when waiting in a long line?",
  "What’s a trick you use to fall asleep faster?",
  "How do you set and track your monthly budget?",
  "What’s your go-to outfit for feeling confident?",
  "How do you handle surprise guests or last-minute plans?",
  "What’s your process for making important decisions quickly?",
  "How do you make boring tasks more fun?",
  "What’s one way you keep your living space organized?",
  "What’s a small thing you do every day to take care of your mental health?",
  "How do you make yourself get out of bed on tough mornings?",
  "What’s your favorite way to relax without spending money?",
  "How do you decide when it’s time to replace something you own?",
  "What’s your method for remembering new names?",
  "How do you manage notifications on your phone?",
  "What’s one thing that always helps you focus when working?",
  "How do you keep your digital files or folders organized?",
  "What’s a simple meal you can make with almost no ingredients?",
  "How do you keep your keys, wallet, or essentials from getting lost?",
  "What’s a small task you do now that makes life easier later?",
  "How do you politely end a conversation when you need to go?",
  "What do you pack when preparing for a short trip?",
  "What’s your favorite way to save time in the morning?",
  "How do you adjust your plans when it suddenly rains?",
  "What do you do when the internet goes out at home?",
  "What’s one errand you enjoy running?",
  "How do you track your monthly expenses or spending?",
  "What’s a low-effort dinner you often make?",
  "What do you do with leftover food at home?",
  "How do you remember to bring reusable bags or bottles?",
  "What’s something you always double-check before leaving the house?",
  "What’s your approach to unsubscribing from junk emails?",
  "How do you deal with minor conflicts at work or school?",
  "What’s your method for keeping your wardrobe neat?",
  "How do you stay motivated to exercise or move your body?",
  "What’s your trick for waking up on time?",
  "How do you prep your space before a video call?",
  "What’s your strategy for choosing what to watch or read next?",
  "How do you keep track of all your passwords safely?",
  "What’s your system for remembering appointments or meetings?",
  "How do you recharge when you’re socially exhausted?",
  "What do you do when you realize you forgot something important?",
  "How do you plan for big purchases?",
  "What’s your trick for cleaning fast when guests are coming over?",
  "How do you keep your phone or computer from feeling cluttered?",
  "What’s something you always do before going to bed?",
  "How do you avoid wasting food at home?",
  "What’s your best advice for staying organized in school or work?",
  "How do you make sure you don’t overcommit your schedule?",
  "What’s a habit you built that made your daily life smoother?",
  "How do you decide when it’s time to rest and take a break?",
  "What’s a simple pleasure that makes your day better?",
  "How do you manage things when you’re running late?",
  "What’s your method for backing up important files?",
  "How do you manage your energy when juggling multiple tasks?",
  "What’s your favorite way to get fresh air during the day?",
  "How do you plan what to eat when dining out?",
  "What’s something you’ve recently decluttered and felt great about?",
  "How do you handle unexpected schedule changes?",
  "What’s your system for keeping up with laundry?",
  "How do you keep your mornings less stressful?",
  "What’s your favorite way to wind down after work or school?",
  "How do you simplify your daily routine when life feels hectic?",
  "What’s one tip you have for sharing a living space?",
  "How do you choose where to spend your free time?",
  "What’s a regular task you’ve completely automated?",
  "How do you find time for hobbies in a busy week?",
  "What’s your process for evaluating if you need something or just want it?",
  "How do you politely say “no” to invitations or events?",
  "What’s one thing you do to prevent forgetting important items?",
  "How do you adjust when a plan doesn’t go as expected?",
  "What’s a productivity hack that works well for you?",
  "How do you manage long wait times at appointments or travel?",
  "What’s your trick for staying comfortable while working or studying?",
  "How do you stay updated without getting overwhelmed by the news?",
  "What’s one thing that makes your morning feel successful?",
  "How do you plan downtime or rest into your week?",
  "What’s a routine that saves you time without sacrificing quality?",
  "How do you keep things clean when you’re super busy?",
  "What’s your personal rule for balancing responsibilities and fun?",
  "What makes you feel truly alive?"
];