const questionsPart6 = [
  "What does success mean to you?",
  "Do you believe people can change? Why or why not?",
  "What’s something you’re afraid to lose?",
  "What are you most grateful for in life right now?",
  "Do you think money can bring happiness?",
  "What helps you feel calm when you're anxious?",
  "What’s a lesson life has taught you recently?",
  "What does freedom mean to you?",
  "Do you believe in fate or free will?",
  "What’s a memory you never want to forget?",
  "What role does family play in your life?",
  "What’s something you’re proud of but rarely talk about?",
  "What do you think happens after we die?",
  "Who understands you the best?",
  "What’s something small that means a lot to you?",
  "What’s your biggest dream right now?",
  "Do you believe everyone deserves a second chance?",
  "What’s one thing you’d like to be remembered for?",
  "When do you feel most like yourself?",
  "What’s a belief you hold that others often don’t agree with?",
  "How do you deal with sadness?",
  "What does “home” mean to you?",
  "What’s something you’ve never said out loud, but wish you could?",
  "What’s the kindest thing someone has ever done for you?",
  "What do you value more: truth or kindness?",
  "What does it mean to live a good life?",
  "If time and money were not a problem, what would you do every day?",
  "What’s something about yourself that you’re still working on?",
  "Do you think people are naturally good or bad?",
  "What makes you feel connected to others?",
  "What’s a fear that you’re trying to overcome?",
  "How do you want to grow in the next year?",
  "What’s a hard decision you had to make?",
  "When do you feel most peaceful?",
  "Who do you trust the most in your life?",
  "What’s something you used to believe but don’t anymore?",
  "What does love mean to you?",
  "What’s a dream you’ve let go of, and why?",
  "Do you think people can truly understand each other?",
  "What’s something you’ve forgiven someone for?",
  "How do you handle failure?",
  "What motivates you to keep going on hard days?",
  "What’s a question you ask yourself often?",
  "If you could tell your younger self one thing, what would it be?",
  "What do you believe is your purpose in life?",
  "What’s something beautiful you saw recently?",
  "What does \"being strong\" mean to you?",
  "What makes life meaningful to you?",
  "What do you think is more important: being right or being kind?",
  "What’s something you’ve always wanted to ask someone but never did?",
  "What does “growing up” mean to you?",
  "How do you know when you’ve truly healed?",
  "What’s a moment in your life that changed everything?",
  "What do you think people misunderstand about you?",
  "What makes a person wise?",
  "What are you pretending not to care about?",
  "How do you define inner strength?",
  "What’s something you wish you could unlearn?",
  "What does it mean to live authentically?",
  "What’s something you’re grateful for today?",
  "What’s a story from your life that shaped who you are?",
  "If time stopped for one hour, what would you do?",
  "What does vulnerability mean to you?",
  "When do you feel the most brave?",
  "What’s something about the world that confuses you?",
  "What kind of person do you feel safest with?",
  "What’s a habit you’re trying to break?",
  "What’s something you know now that you didn’t a year ago?",
  "How do you recover from failure?",
  "What kind of conversations energize you?",
  "What does it mean to be seen?",
  "What helps you build trust with someone?",
  "What’s something you admire in your younger self?",
  "What would you do differently if you weren’t afraid?",
  "What’s something you’ve forgiven yourself for?",
  "What makes someone unforgettable?",
  "When was the last time you felt truly alive?",
  "What’s something you’d like to understand better?",
  "Who has had the biggest impact on your life?",
  "What emotion do you find hardest to express?",
  "How do you deal with regret?",
  "What part of your past still feels unresolved?",
  "What does “being enough” mean to you?",
  "What keeps you grounded when life feels chaotic?",
  "What’s one lesson you keep learning over and over again?",
  "When do you feel most creative?",
  "What does it mean to live without fear?",
  "What’s something that gives you comfort during hard times?",
  "How do you handle emotional pain?",
  "What makes you feel fulfilled?",
  "What role does hope play in your life?",
  "What’s a belief that guides the way you live?",
  "What do you wish people asked you more often?",
  "How do you define peace?",
  "What’s something you’ve said that you wish you could take back?",
  "When do you feel the most disconnected from others?",
  "What’s one thing you never want to forget?",
  "What helps you make sense of the world?",
  "What does it mean to truly listen?",
  "When was the last time you truly felt at peace?",
  "What does “home” mean to you?",
  "What do you believe is your purpose in life?",
  "What scares you more: failure or success?",
  "How has your definition of love changed over time?",
  "What part of yourself are you still learning to accept?",
  "If your emotions could speak, what would they say right now?",
  "What’s a question you wish more people asked themselves?",
  "When do you feel most in tune with your values?",
  "What memory do you revisit the most, and why?",
  "What do you believe happens when we die?",
  "What do you think your future self would thank you for today?",
  "What do you most need to hear right now?",
  "What’s a truth you’ve been avoiding?",
  "What does “living fully” look like for you?",
  "What’s something that’s easy for others but hard for you?",
  "What do you think is the meaning of suffering?",
  "What relationship taught you the most about yourself?",
  "What kind of legacy do you want to leave behind?",
  "How do you usually react to uncertainty?",
  "What would you say to your inner child?",
  "How do you know when it’s time to let go?",
  "What helps you feel connected to something bigger than yourself?",
  "What does honesty mean in your life right now?",
  "What’s a question you ask yourself too often?",
  "What makes life beautiful, even in pain?",
  "What kind of silence do you find comforting?",
  "What would you do if you had nothing to prove?",
  "What personal truth have you recently discovered?",
  "What’s something you’ve never told anyone?",
  "When do you feel most whole?",
  "What fear have you outgrown?",
  "What do you do when you feel lost?",
  "How do you define “being alive”?",
  "What’s something you’re holding onto that no longer serves you?",
  "What memory do you wish you could relive?",
  "What belief system guides your decisions?",
  "What would you ask a version of yourself 10 years from now?",
  "When was the last time you felt truly understood?",
  "How do you handle inner conflict?",
  "What makes you feel spiritually nourished?",
  "What are you still curious about?",
  "If you had to give your life a title, what would it be?",
  "What brings you back to yourself when you feel scattered?",
  "What does it mean to forgive someone who isn’t sorry?",
  "What’s something you’ve learned the hard way?",
  "What do you think your past self would be proud of?",
  "When do you feel closest to your true self?",
  "What question do you hope no one ever asks you?",
  "What’s one part of your identity that’s changed recently?",
  "What does happiness mean to you?",
  "How do you find meaning in difficult times?",
  "What’s a value you refuse to compromise on?",
  "When was the last time you felt truly free?",
  "What do you think love requires most?",
  "How do you react when your beliefs are challenged?",
  "What’s something you wish you could change about the world?",
  "What do you want your life to teach others?",
  "What’s a question you’re afraid to answer honestly?",
  "How do you handle disappointment in yourself?",
  "What does it mean to live a life with purpose?",
  "What does it feel like to forgive someone deeply?",
  "What’s something you’ve done that scared you but you’re proud of?",
  "What do you believe about the power of kindness?",
  "How do you stay hopeful when things feel hopeless?",
  "What’s something you’ve lost that changed you?",
  "What role does faith or spirituality play in your life?",
  "How do you know when you’re growing?",
  "What’s one way you’d like to improve your relationships?",
  "What does it mean to be vulnerable?",
  "How do you deal with feelings of loneliness?",
  "What’s something you wish you told your parents?",
  "What do you think is the biggest lesson life has taught you so far?",
  "How do you express your true self to others?",
  "What’s a fear you’d like to overcome?",
  "What’s the most difficult choice you’ve ever made?",
  "How do you find balance in life?",
  "What does it mean to be authentic?",
  "What’s something you’re most proud of about yourself?",
  "What do you believe about fate?",
  "What’s something you want to do before you die?",
  "How do you nurture your mental health?",
  "What does forgiveness look like for you?",
  "What makes you feel most alive?",
  "What’s a dream you’re still working on?",
  "How do you deal with failure?",
  "What’s something you’ve learned about love?",
  "What does success mean beyond money and career?",
  "What’s your biggest hope for the future?",
  "What does it mean to live in the present moment?",
  "What’s something you’ve never told your closest friend?",
  "How do you find peace after conflict?",
  "What do you think happens when people change?",
  "How do you define wisdom?",
  "What’s a habit that has helped you grow?",
  "What do you want to be remembered for?",
  "What’s something that always inspires you?",
  "How do you practice gratitude?",
  "What’s a question you’d ask a wise person?",
  "What does it mean to be compassionate?",
  "How do you face your fears?",
  "What’s a moment when you felt completely understood?",
  "What’s something you’d like to teach others?",
  "How do you stay motivated during hard times?",
  "What’s a belief that changed your life?",
  "What does it mean to be humble?",
  "How do you handle criticism?",
  "What’s a truth you’ve recently discovered?",
  "What does happiness look like for you?",
  "How do you build meaningful connections?",
  "What’s a risk you’re glad you took?",
  "What’s something you’ve done to grow emotionally?",
  "How do you define personal success?",
  "What does it mean to love yourself?",
  "What’s a challenge that made you stronger?",
  "How do you stay true to your values?",
  "What’s something you’ve let go of recently?",
  "What does peace of mind feel like?",
  "How do you practice self-compassion?",
  "What’s a memory that shaped your worldview?",
  "What’s something you’re curious about?",
  "How do you stay connected to your passions?",
  "What does it mean to be resilient?",
  "What’s a lesson you learned from a mistake?",
  "How do you know when to trust someone?",
  "What’s a moment that made you feel grateful?",
  "What do you think about forgiveness and forgetting?",
  "How do you handle uncertainty?",
  "What’s a dream that scares you?",
  "How do you express your creativity?",
  "What does it mean to have integrity?",
  "What’s something you want to improve about yourself?",
  "How do you nurture your relationships?",
  "What’s a time when you felt truly alive?",
  "What does it mean to be kind to yourself?",
  "How do you stay hopeful in difficult times?",
  "What’s a value you want to pass on?",
  "How do you handle regret?",
  "What’s a question you often ask yourself?",
  "What does living authentically mean to you?",
  "How do you show love to others?",
  "What’s a lesson you learned from a loved one?",
  "How do you find joy in everyday life?",
  "What does courage mean to you?",
  "What’s something you want to change about the world?",
  "How do you practice mindfulness?",
  "What’s a belief that guides your decisions?",
  "How do you handle disappointment?",
  "What’s a question that challenges you?",
  "What does it mean to live a meaningful life?",
  "What’s something you’ve struggled to accept about yourself?",
  "How do you find balance between your needs and others’ needs?",
  "What does it mean to forgive yourself?",
  "When do you feel most connected to nature?",
  "How do you define true friendship?",
  "What’s a dream you’ve put on hold?",
  "What does it mean to be vulnerable with others?",
  "How do you overcome self-doubt?",
  "What’s a belief that has been challenged recently?",
  "What does it feel like to be truly understood?",
  "What’s a moment when you felt deeply grateful?",
  "How do you practice patience in difficult situations?",
  "What’s something that always lifts your spirit?",
  "How do you stay grounded during stressful times?",
  "What’s a lesson you learned from failure?",
  "How do you define personal growth?",
  "What’s a value you try to live by every day?",
  "What does it mean to live with intention?",
  "How do you cope with loss?",
  "What’s a fear that you’ve overcome?",
  "How do you know when to trust your intuition?",
  "What’s something that inspires your creativity?",
  "How do you express your emotions?",
  "What’s a question you’d ask your future self?",
  "What does happiness look like in your daily life?",
  "How do you handle moments of loneliness?",
  "What’s something you want to learn more about?",
  "What does it mean to be compassionate to yourself?",
  "How do you nurture your passions?",
  "What’s a habit that helps your mental well-being?",
  "What does it mean to be present in the moment?",
  "How do you deal with uncertainty in life?",
  "What’s a belief that gives you strength?",
  "How do you celebrate your successes?",
  "What’s something you’ve done that surprised you?",
  "How do you show love to those around you?",
  "What’s a challenge you’re currently facing?",
  "How do you maintain hope in tough times?",
  "What does it mean to be authentic in relationships?",
  "How do you handle criticism from others?",
  "What’s a quality you admire in yourself?",
  "How do you practice self-care?",
  "What’s a moment when you felt completely at peace?",
  "What does freedom mean to you personally?",
  "How do you express gratitude in your life?",
  "What’s something you’re passionate about?",
  "How do you stay motivated to pursue your goals?",
  "What does it mean to live a balanced life?",
  "What’s a mistake that taught you an important lesson?",
  "How do you define emotional strength?",
  "What’s a fear that has held you back?",
  "How do you find joy in simple things?",
  "What does success mean beyond material wealth?",
  "How do you reconnect with yourself after stress?",
  "What’s a moment when you felt truly alive?",
  "How do you practice forgiveness in your daily life?",
  "What does it mean to be kind to others?",
  "How do you handle change and uncertainty?",
  "What’s a belief that has guided your choices?",
  "How do you show empathy?",
  "What’s a question that challenges your perspective?",
  "How do you maintain hope during difficult periods?",
  "What does it mean to be resilient?",
  "How do you cope with feelings of failure?",
  "What’s a value you hold that others might not understand?",
  "How do you find meaning in everyday life?",
  "What’s a lesson you learned from a relationship?",
  "How do you define love in your life?",
  "What’s something you’ve done to grow emotionally?",
  "How do you maintain healthy boundaries?",
  "What’s a moment that changed your outlook on life?",
  "How do you practice mindfulness daily?",
  "What does it mean to live without regrets?",
  "How do you cultivate gratitude?",
  "What’s a quality you seek in others?",
  "How do you nurture your mental health?",
  "What’s a fear you’ve recently confronted?",
  "How do you express your true self?",
  "What does it mean to forgive others?",
  "How do you balance ambition and contentment?",
  "What’s a challenge that made you stronger?",
  "How do you find peace after conflict?",
  "What’s something you want to let go of?",
  "How do you stay hopeful about the future?",
  "What’s a question you ask yourself often?",
  "What does it mean to be emotionally intelligent?",
  "How do you support others in their growth?",
  "What’s something you’ve learned from failure?",
  "How do you maintain authenticity in your life?",
  "What’s a memory that always brings you joy?",
  "How do you find strength in vulnerability?",
  "What does it mean to be present for someone?",
  "How do you practice self-reflection?",
  "What’s a belief you want to pass on?",
  "How do you show gratitude to yourself?",
  "What’s something you’ve recently learned about yourself?",
  "How do you cope with disappointment?",
  "What does it mean to live with purpose?",
  "How do you express kindness in difficult situations?",
  "What’s a personal goal you’re working towards?",
  "What’s something you’ve always wanted to explore?",
  "How do you handle feelings of jealousy?",
  "What does it mean to live a meaningful life for you?",
  "How do you define happiness?",
  "What role does gratitude play in your life?",
  "When do you feel most vulnerable?",
  "How do you recover from emotional pain?",
  "What’s something you wish you could tell your past self?",
  "What does true friendship mean to you?",
  "How do you balance your needs with the needs of others?",
  "What’s a moment that shaped your character?",
  "How do you deal with uncertainty?",
  "What do you believe about second chances?",
  "What’s a value you want to pass on to future generations?",
  "How do you express love without words?",
  "What does forgiveness look like for you?",
  "How do you stay true to yourself in challenging situations?",
  "What’s a lesson you learned from someone you admire?",
  "What do you think about the idea of destiny?",
  "How do you cope with feelings of loneliness?",
  "What’s something you’ve done that changed your perspective?",
  "How do you nurture your inner peace?",
  "What does it mean to be free?",
  "What motivates you to keep going during tough times?",
  "How do you practice self-awareness?",
  "What’s a dream you still want to achieve?",
  "How do you handle conflict in relationships?",
  "What’s something you’ve had to forgive yourself for?",
  "What does living authentically mean to you?",
  "How do you find hope after loss?",
  "What’s a quality you admire in others?",
  "How do you cultivate empathy?",
  "What’s a belief that has evolved for you over time?",
  "How do you show compassion to yourself?",
  "What does it mean to be resilient?",
  "How do you celebrate your achievements?",
  "What’s a fear that you’re working to overcome?",
  "How do you find joy in everyday moments?",
  "What does it mean to be emotionally strong?",
  "How do you maintain meaningful connections?",
  "What’s something you wish more people understood about life?",
  "How do you deal with regret?",
  "What’s a personal value you hold dear?",
  "How do you practice mindfulness?",
  "What’s a moment when you felt truly alive?",
  "How do you support others through their struggles?",
  "What does it mean to love unconditionally?",
  "How do you handle disappointment?",
  "What’s a question you ask yourself when you need guidance?",
  "How do you define success beyond material things?",
  "What’s a moment you’re most proud of?",
  "How do you find balance in your life?",
  "What does it mean to be grateful?",
  "How do you express your true self?",
  "What’s a lesson you learned the hard way?",
  "How do you cope with change?",
  "What does living with purpose look like for you?",
  "How do you find peace in chaos?",
  "What’s a quality you strive to develop?",
  "How do you nurture your mental health?",
  "What’s a fear you’ve conquered?",
  "How do you practice forgiveness in difficult situations?",
  "What does it mean to be kind to yourself?",
  "How do you handle moments of self-doubt?",
  "What’s something that inspires you daily?",
  "How do you stay hopeful about the future?",
  "What does it mean to live with integrity?",
  "How do you express gratitude to those around you?",
  "What’s a personal challenge you’ve overcome?",
  "How do you cultivate self-love?",
  "What does it mean to be present in the moment?",
  "How do you navigate difficult emotions?",
  "What’s a belief that guides your life decisions?",
  "How do you show empathy in your daily life?",
  "What’s a memory that brings you comfort?",
  "How do you maintain authenticity?",
  "What does it mean to have courage?",
  "How do you support your personal growth?",
  "What’s a quality you appreciate in your friends?",
  "How do you deal with feelings of inadequacy?",
  "What does it mean to live fully?",
  "How do you practice self-reflection?",
  "What’s a lesson you learned from failure?",
  "How do you maintain hope during challenges?",
  "What does it mean to be emotionally intelligent?",
  "How do you nurture meaningful relationships?",
  "What’s a moment that made you feel connected?",
  "How do you express kindness to strangers?",
  "What’s a fear that has held you back?",
  "How do you practice patience?",
  "What does it mean to be humble?",
  "How do you find meaning in everyday experiences?",
  "What’s something you want to improve about yourself?",
  "How do you handle criticism constructively?",
  "What does it mean to be self-aware?",
  "How do you practice gratitude regularly?",
  "What’s a challenge that helped you grow?",
  "How do you express your creativity?",
  "What does it mean to be compassionate?",
  "How do you stay motivated?",
  "What’s a moment that changed your perspective?",
  "How do you find joy in small things?",
  "What does it mean to be authentic in your relationships?",
  "How do you practice self-compassion?",
  "What’s a belief that has evolved for you?",
  "How do you nurture your passions?",
  "What does it mean to forgive others?",
  "How do you stay grounded during stress?",
  "What’s a lesson you learned from a mentor?",
  "How do you express your values?",
  "What does it mean to live without regrets?",
  "How do you cope with loss?",
  "What’s a question you ask yourself often?",
  "How do you find peace after conflict?",
  "What does it mean to love yourself?",
  "How do you handle feelings of loneliness?",
  "What’s a personal value you live by?",
  "How do you cultivate resilience?",
  "What does it mean to be present?",
  "How do you show gratitude in difficult times?",
  "What’s a moment when you felt truly understood?",
  "How do you nurture your mental well-being?",
  "What does it mean to be courageous?",
  "How do you express kindness in challenging situations?",
  "What’s a belief that gives you strength?",
  "How do you support others in their growth?",
  "What does it mean to live intentionally?",
  "How do you maintain hope during adversity?",
  "What’s a lesson you learned from a mistake?",
  "How do you stay true to your values?",
  "What does it mean to be emotionally strong?",
  "How do you find joy in everyday life?",
  "What’s a fear you’re working to overcome?",
  "How do you express your true self?",
  "What does forgiveness mean to you?",
  "How do you balance ambition with contentment?",
  "What’s a challenge that made you stronger?",
  "How do you find peace after hardship?",
  "What’s something you want to let go of?",
  "How do you cultivate empathy?",
  "What does it mean to be kind to yourself?",
  "How do you handle disappointment?",
  "What’s a question that challenges your thinking?",
  "How do you find meaning in your daily life?",
  "What does it mean to live with purpose?",
  "How do you express love to others?",
  "What’s a lesson you learned from a difficult experience?",
  "How do you practice mindfulness?",
  "What does it mean to be authentic?",
  "How do you nurture meaningful connections?",
  "If you could have any superpower for a day, what would it be?"
];