const questionsPart1 = [
  "What’s something most people don’t know about you?",
  "What makes you feel truly alive?",
  "What’s your favorite way to spend a weekend?",
  "What’s a song that brings back strong memories for you?",
  "What are you passionate about lately?",
  "What’s your go-to comfort food?",
  "If you could live anywhere in the world, where would it be?",
  "What kind of people do you feel safest around?",
  "What’s a book or movie that changed how you see the world?",
  "What’s your most irrational fear?",
  "What’s your favorite time of day, and why?",
  "What did you want to be when you were a kid?",
  "Do you believe in soulmates?",
  "What’s something that instantly makes you smile?",
  "What’s a skill you wish you had?",
  "What does your perfect day look like?",
  "How do you usually make new friends?",
  "What kind of people do you feel drawn to?",
  "What role does family play in your life?",
  "What’s your biggest dream right now?",
  "What’s something you’re proud of but rarely talk about?",
  "What helps you feel calm when you're anxious?",
  "Who understands you the best?",
  "What’s a small thing that means a lot to you?",
  "What’s a memory that makes you laugh every time?",
  "What was your first impression of me?",
  "What do you value most in a friendship?",
  "What’s something you’ve never done but would like to try?",
  "What’s your idea of love?",
  "Do you think people change over time?",
  "What do you notice first when meeting someone?",
  "What’s something you’ve unlearned recently?",
  "Who is someone you admire deeply?",
  "What does “home” mean to you?",
  "What kind of childhood did you have?",
  "Do you like to plan things or be spontaneous?",
  "What makes you feel seen?",
  "How do you like to receive affection?",
  "Do you believe in fate or free will?",
  "What’s something you wish more people understood about you?",
  "What’s your favorite way to express yourself?",
  "What are your dealbreakers in a relationship?",
  "Do you tend to follow your head or your heart?",
  "What’s one thing you’ve always been curious about?",
  "How do you show someone you care?",
  "What motivates you to keep going during hard times?",
  "What’s your biggest personal growth moment so far?",
  "What makes you feel appreciated?",
  "How do you usually deal with conflict?",
  "What kind of environment helps you thrive?",
  "What’s something you’re learning about yourself right now?",
  "What’s your attachment style in relationships?",
  "What does trust mean to you?",
  "What’s a belief you’ve outgrown?",
  "How do you define success?",
  "Who is someone that shaped your life significantly?",
  "What are your love languages?",
  "When do you feel most like yourself?",
  "How do you define “home” emotionally?",
  "What makes you feel emotionally safe?",
  "What’s something that made you who you are today?",
  "Do you enjoy deep conversations or light-hearted ones more?",
  "What does “being present” mean to you?",
  "What kind of legacy do you want to leave?",
  "What’s your favorite kind of connection with someone?",
  "What helps you feel close to someone?",
  "Do you believe people can really understand each other?",
  "What’s a core memory you cherish?",
  "What do you most want to be remembered for?",
  "What’s something you feel you’ve healed from?",
  "What does your inner voice usually sound like?",
  "When do you feel most at peace?",
  "What’s something new you’ve learned about yourself this year?",
  "How do you comfort yourself when things get hard?",
  "What’s a value you hold dearly?",
  "How would your childhood self describe who you are now?",
  "What’s something that instantly warms your heart?",
  "Who in your life makes you feel most understood?",
  "What’s a lesson you’ve had to learn the hard way?",
  "What’s something that makes you feel connected to the world?",
  "How do you express vulnerability?",
  "What’s something you’d like to ask your future self?",
  "What’s a moment when you felt truly known?",
  "How do you like to bond with others?",
  "What’s one thing that surprises people when they get to know you?",
  "Do you find it easy to open up to others?",
  "What’s a conversation you’ll never forget?",
  "How do you navigate misunderstandings?",
  "When do you feel most inspired?",
  "What makes a connection meaningful to you?",
  "What are you most grateful for today?",
  "What’s something you hope people see in you?",
  "What’s your most cherished tradition?",
  "What does friendship mean to you right now?",
  "What helps you trust someone?",
  "How do you recharge emotionally?",
  "What are you curious about in others?",
  "What’s a question you wish people asked you more often?",
  "What does emotional intimacy mean to you?",
  "What’s a tradition from your culture that you love?",
  "What’s your favorite way to start the day?",
  "What’s a smell that brings back memories for you?",
  "Do you prefer quiet nights or social gatherings?",
  "What do you look for in a new friend?",
  "What’s your favorite memory from the past year?",
  "What’s your comfort movie or TV show?",
  "Do you prefer deep talks or shared activities to connect with others?",
  "What’s your favorite season, and why?",
  "What’s something that makes you feel nostalgic?",
  "How do you usually celebrate your birthday?",
  "Who do you turn to when you need support?",
  "What’s something you enjoy doing alone?",
  "What kind of music lifts your mood?",
  "What’s your favorite childhood game?",
  "Do you like surprises? Why or why not?",
  "What’s a meaningful compliment you’ve received?",
  "How do you stay connected with long-distance friends?",
  "What’s a tradition you’d like to start?",
  "What makes you feel included in a group?",
  "What’s something you always carry with you?",
  "What kind of conversations do you enjoy most?",
  "Do you enjoy giving or receiving gifts more?",
  "What’s something you miss about being a kid?",
  "What helps you feel grounded?",
  "What’s a hobby you wish more people appreciated?",
  "How do you usually spend your holidays?",
  "What’s something small that makes your day better?",
  "What’s your favorite kind of shared activity with friends?",
  "What’s a snack that reminds you of home?",
  "Do you prefer planned hangouts or spontaneous ones?",
  "What’s a way you show love to people close to you?",
  "What’s a question you wish people asked you more?",
  "What’s a memory that always makes you feel loved?",
  "Who’s someone that helped shape your values?",
  "What makes someone a good listener?",
  "What’s something you like about your current stage of life?",
  "What’s a moment you felt truly appreciated?",
  "What does “being authentic” mean to you?",
  "What’s a nickname you’ve had, and how did you get it?",
  "How do you build trust with someone new?",
  "What’s something you love about your hometown?",
  "What’s something that instantly makes you laugh?",
  "Who is someone you’ve recently reconnected with?",
  "What helps you feel energized in social situations?",
  "Do you prefer group outings or one-on-one time?",
  "What’s a fun fact about you?",
  "What’s your favorite way to spend a rainy day?",
  "What’s something you enjoy that others find unusual?",
  "What’s a topic you could talk about for hours?",
  "What’s a special family tradition you cherish?",
  "How do you usually greet new people?",
  "What’s your idea of quality time with someone?",
  "What’s something people often misunderstand about you?",
  "What’s a personal ritual that brings you comfort?",
  "Do you consider yourself more introverted or extroverted?",
  "What’s a moment you felt truly at home?",
  "What kind of people do you feel energized around?",
  "What’s something you hope to share with future generations?",
  "What’s a compliment that’s stuck with you?",
  "How do you stay true to yourself in new environments?",
  "What’s a phrase or quote that resonates with you?",
  "What’s your favorite way to make someone’s day better?",
  "What’s something that makes you feel appreciated at work or school?",
  "What do you usually talk about when you first meet someone?",
  "What’s a gesture that makes you feel cared for?",
  "What’s a way you enjoy connecting with people online?",
  "What kind of presence do you hope to have in people’s lives?",
  "What’s a song lyric that feels personal to you?",
  "Do you prefer phone calls or text messages?",
  "What’s your favorite kind of weekend plan?",
  "What do you notice first when you feel close to someone?",
  "What helps you open up to others?",
  "What’s a place that feels like a second home?",
  "How do you usually introduce yourself?",
  "What’s a small act of kindness that left a big impact on you?",
  "What’s something you associate with comfort?",
  "What’s your go-to way to relax?",
  "What’s something that reminds you of your childhood?",
  "What’s your favorite way to show someone they matter?",
  "What’s a memory you’d love to relive?",
  "Do you prefer writing or speaking when expressing yourself?",
  "What’s something you feel confident doing?",
  "Who’s someone that’s been there for you through a tough time?",
  "What’s something that helps you feel understood?",
  "What’s a routine that brings you joy?",
  "What makes someone feel “real” to you?",
  "What’s something that gives you a sense of belonging?",
  "What’s a place that holds special meaning for you?",
  "What helps you feel present in the moment?",
  "What’s something you appreciate about your culture?",
  "What’s your favorite shared activity with friends or family?",
  "What’s a kind gesture you’ll never forget?",
  "What’s a sound that soothes you?",
  "Who’s someone you admire for how they treat others?",
  "What’s something that helps you recharge socially?",
  "What’s a way you stay connected to your roots?",
  "What’s a food that brings you comfort?",
  "What kind of environments make you feel inspired?",
  "What’s something you enjoy doing slowly?",
  "What’s something you’ve recently rediscovered about yourself?",
  "What’s your favorite way to wind down after a long day?",
  "How do you usually cheer someone up?",
  "What’s a simple pleasure you look forward to?",
  "What kind of conversations help you feel seen?",
  "Who’s someone you’ve learned a lot from just by observing them?",
  "What’s a way you express love without words?",
  "What’s something that instantly calms you down?",
  "How do you like to celebrate small wins?",
  "What does “quality time” look like for you?",
  "What’s a way you like to welcome new people into a group?",
  "Do you believe people can stay friends forever?",
  "What’s a personality trait you value in others?",
  "What do you find most attractive in a person—not physically?",
  "What makes you feel like you belong somewhere?",
  "What kind of compliments mean the most to you?",
  "What does “support” look like to you in tough times?",
  "What’s something you love doing that doesn’t involve screens?",
  "What kind of people do you feel most relaxed around?",
  "What’s a shared experience that helped deepen a friendship?",
  "What kind of stories do you enjoy hearing from others?",
  "What do you usually notice about someone’s energy?",
  "What’s something that reveals a lot about someone, in your opinion?",
  "How do you decide whether you can trust someone?",
  "What’s a way you bond with others over food?",
  "What’s something you and your friends always laugh about?",
  "What helps you open up in new situations?",
  "What’s something your friends know you for?",
  "What do you love most about your closest friend?",
  "What’s something people do that makes you feel respected?",
  "What kind of first impression do you hope to give?",
  "What’s a way someone surprised you in a good way?",
  "What kind of social events do you actually enjoy?",
  "What’s a feeling you associate with home?",
  "What’s something you learned from a meaningful connection?",
  "What helps you recognize when someone genuinely cares?",
  "What’s your favorite memory involving laughter?",
  "What’s a friendship that shaped how you view relationships?",
  "What kind of legacy do you want to leave among your friends?",
  "What does being “emotionally available” mean to you?",
  "What’s something you value more now than you used to?",
  "How do you handle awkward silences in conversations?",
  "What do you love most about connecting with others?",
  "What’s a moment of kindness you’ll always remember?",
  "What’s a way you like to make people feel welcome?",
  "What’s a gesture of love that you remember from your family?",
  "What’s a place that always brings you peace?",
  "How do you show appreciation to the people in your life?",
  "What’s something you’ve forgiven yourself for?",
  "What’s something you’ve forgiven someone else for?",
  "What’s your favorite thing to do on a lazy day?",
  "What’s your favorite kind of surprise?",
  "What’s a time you felt really proud of a friend?",
  "How do you maintain your friendships over time?",
  "What’s something you enjoy about meeting new people?",
  "What do you think makes a conversation memorable?",
  "What’s something you’ve learned about love over the years?",
  "How do you usually say goodbye to someone special?",
  "What makes a shared silence feel comforting instead of awkward?",
  "How do you like to show encouragement to others?",
  "What’s a moment that made you feel very understood?",
  "What’s something you love talking about with close friends?",
  "What’s your favorite way to connect with someone across distance?",
  "Who do you feel most “yourself” around?",
  "What’s something you’ve done to make someone feel special?",
  "What’s a non-verbal way you express care or affection?",
  "When do you feel most grateful for your friendships?",
  "What’s a shared tradition you have with a friend or group?",
  "What’s your love language, and how do you show it?",
  "What’s a way you’ve grown because of a relationship?",
  "What’s a time when someone surprised you with empathy?",
  "What helps you reconnect with yourself?",
  "What does “emotional safety” mean to you?",
  "What’s something you admire in a mentor or teacher?",
  "What’s something small that makes you feel noticed?",
  "How do you remember important details about others?",
  "What helps you feel confident in a new environment?",
  "What’s a compliment you like to give others?",
  "What’s something you’re working on in your relationships?",
  "What’s your ideal kind of first date or hangout?",
  "How do you repair a relationship after a conflict?",
  "What’s something that helps you feel emotionally refreshed?",
  "How do you celebrate your friends’ successes?",
  "What’s a way someone earned your trust?",
  "What’s a way someone lost your trust?",
  "What makes you feel like someone truly “gets” you?",
  "How do you know when you’ve really clicked with someone?",
  "What’s your favorite form of human connection?",
  "What’s something you wish people took more time to notice?",
  "What do you miss about old friendships?",
  "How do you usually start meaningful conversations?",
  "What kind of space helps you feel open to connecting?",
  "What’s a feeling you chase in relationships?",
  "What does “mutual respect” mean to you?",
  "What kind of people are you naturally drawn to?",
  "How do you comfort someone going through a hard time?",
  "What’s something you hope to teach others through your relationships?",
  "What does kindness mean to you in everyday life?",
  "What’s something you’ve learned from being vulnerable?",
  "How do you reconnect with someone after losing touch?",
  "What’s something you’d like to be remembered for by your friends?",
  "What’s a piece of advice that really stuck with you?",
  "What makes you feel “at home” in someone’s presence?",
  "How do you like to be celebrated on special occasions?",
  "What’s something that makes you feel proud of who you are?",
  "When do you feel closest to people?",
  "What kind of energy do you hope to bring into a room?",
  "What’s something you try to bring into all your relationships?",
  "What’s a small act that shows big love?",
  "What makes a place feel welcoming to you?",
  "What helps you know that someone values your presence?",
  "How do you usually respond when someone opens up to you?",
  "What’s a personality trait you’ve learned to appreciate more over time?",
  "How do you define “emotional intelligence”?",
  "What makes you feel like your presence matters?",
  "What’s something you always want to give your loved ones?",
  "What do you admire about how kids make friends so easily?",
  "How do you express love in times of stress or busyness?",
  "What’s something you want more of in your daily life?",
  "What helps you deepen a casual acquaintance into a real connection?",
  "What makes you feel part of something bigger than yourself?",
  "What’s your favorite thing about your chosen family or friend group?",
  "How do you show someone they can count on you?",
  "What’s your favorite way to make memories with others?",
  "When do you feel your most generous self?",
  "How do you express joy around others?",
  "What makes someone feel magnetic to you?",
  "What’s something you admire in a good communicator?",
  "What do you do to create emotional closeness?",
  "What does “being there” for someone look like to you?",
  "What’s a non-material gift that means a lot to you?",
  "How do you typically express forgiveness?",
  "What does it mean to feel emotionally full?",
  "What’s a small way someone showed you you mattered?",
  "How do you nurture the relationships that are important to you?",
  "What’s something you do differently because of someone you care about?",
  "When do you feel most patient with others?",
  "What does “showing up” mean to you in a friendship?",
  "What do you love most about people-watching?",
  "What helps you let your guard down with someone?",
  "What’s a story about you that your friends like to tell?",
  "What makes someone feel dependable to you?",
  "What do you do when someone needs space but you still want to support them?",
  "What’s a funny memory that brings you joy again and again?",
  "How do you hold space for someone else’s emotions?",
  "What do you want to learn about the people closest to you?",
  "How do you handle misunderstandings in conversations?",
  "What’s something that helps you stay present when listening?",
  "What’s something you admire about how your parents/family relate to others?",
  "What makes someone feel “home-like” to you?",
  "How do you show someone they can trust you with their secrets?",
  "What does being “fully yourself” in front of someone feel like?",
  "What do you do to make others feel heard?",
  "What kind of feedback feels most helpful to you?",
  "What helps you forgive someone who hurt you?",
  "When do you feel like you’re part of a team?",
  "What do you value more: honesty or harmony? Why?",
  "What’s something you never get tired of sharing with others?",
  "What’s a way someone made your day better recently?",
  "What’s something you do that makes others smile?",
  "What’s your favorite way to surprise someone?",
  "What’s a relationship habit that works well for you?",
  "When do you feel like you’re growing through a relationship?",
  "How do you know when someone “gets” your sense of humor?",
  "What does “mutual understanding” feel like to you?",
  "What’s something you’ve learned through disagreement?",
  "What does it mean to “hold space” for someone else?",
  "What makes you feel chosen in a friendship or relationship?",
  "What’s something you’ve taught a friend recently?",
  "What’s something a friend has taught you?",
  "What kind of boundaries help you thrive in relationships?",
  "What helps you express yourself clearly during emotional moments?",
  "What’s your favorite kind of “just because” message to send or receive?",
  "What’s something you do to celebrate your friends’ uniqueness?",
  "How do you bring warmth into conversations?",
  "When do you feel proud of how you treat others?",
  "What’s something you’ve done that made someone else feel truly seen?",
  "How do you communicate when you’re feeling overwhelmed?",
  "What does a balanced relationship feel like to you?",
  "What do you need most from others when you’re going through a hard time?",
  "What’s something someone said that changed how you see yourself?",
  "How do you hold on to meaningful connections over time?",
  "What helps you connect with someone from a different background?",
  "What’s a question you love asking new people?",
  "What makes a first meeting memorable to you?",
  "What’s a shared value that helps build connection for you?",
  "What kind of acts of service mean the most to you?",
  "What do you usually remember most after meeting someone?",
  "What helps you be more patient with others?",
  "How do you like to celebrate milestones with loved ones?",
  "What kind of encouragement means the most to you?",
  "How do you reflect care through everyday gestures?",
  "What’s a way someone helped you during a time of transition?",
  "What’s your favorite thing to do with people you care about?",
  "How do you maintain a balance between giving and receiving in relationships?",
  "What’s something you’ve learned about human nature through connection?",
  "What do you think builds lasting trust between people?",
  "What’s something you try to be mindful of when relating to others?",
  "What does “growing together” mean to you?",
  "What’s something someone said that helped you feel worthy?",
  "What do you most enjoy sharing with others?",
  "What’s something you do that feels like an act of love?",
  "How do you like to honor people’s milestones (birthdays, achievements, etc.)?",
  "What do you admire about how children make friends?",
  "What helps you recover after a falling out with someone?",
  "What do you do to make space for others’ emotions?",
  "What’s a quality you try to embody in all your relationships?",
  "What’s something people often thank you for?",
  "What’s your favorite way to stay close with someone over time?",
  "What does it mean to truly listen to someone?",
  "What’s a way you show up for friends even when you’re tired?",
  "What kind of emotional support do you offer best?",
  "What’s something you’ve done for someone “just because”?",
  "What’s a time you felt really connected to a stranger?",
  "What’s your favorite way to connect through creativity?",
  "What do you wish people felt safer sharing with each other?",
  "What’s something that makes you feel completely accepted?",
  "How do you keep conversations meaningful, not surface-level?",
  "What’s something you’ve realized about friendship as you’ve gotten older?",
  "What do you notice about someone’s eyes when they talk?",
  "What’s a memory where you felt really included?",
  "How do you rebuild connection after conflict?",
  "What’s something you love about your favorite friendships?",
  "What’s something you like to do together in silence?",
  "What role does humor play in your relationships?",
  "How do you support friends who are going through change?",
  "What’s something that feels sacred in your closest relationships?",
  "How do you express appreciation without words?",
  "What’s a type of vulnerability that makes you feel closer to someone?",
  "What’s something that brings your friendships to life?",
  "What’s your favorite kind of long conversation?",
  "What do you do when a friend pulls away emotionally?",
  "What do you want to be known for in your personal relationships?",
  "How do you like to create shared memories?",
  "What helps you feel emotionally regulated in social settings?",
  "What’s something you find beautiful about people in general?",
  "What’s something you hope to be better at in relationships?",
  "What’s your favorite way to show loyalty?",
  "How do you know when you’ve found a true friend?",
  "What’s something you believe about the power of connection?",
  "How do you make people feel welcomed in your space?",
  "What’s a quality in someone that always earns your respect?",
  "What do you think keeps people emotionally distant?",
  "What do you appreciate about how others express love?",
  "What’s something you want more of in your social life?",
  "What makes a relationship feel effortless to you?",
  "How do you handle being misunderstood by someone close?",
  "What makes you feel “safe to be weird”?",
  "What’s something you always try to notice in others?",
  "What’s a boundary that’s helped your relationships flourish?",
  "How do you help others feel less alone?",
  "What do you value most in your closest relationships?",
  "What’s something you enjoy doing for others without expecting anything back?",
  "How do you express emotional honesty with kindness?",
  "What’s your favorite memory of feeling truly connected to someone?",
  "What do you do when you want to reconnect with someone?",
  "What’s something you’ve learned about empathy?",
  "How do you protect your peace while staying open to connection?",
  "What helps you recognize a genuine connection?",
  "What’s a feeling you chase in your relationships?",
  "What helps you stay grounded when connecting with many people at once?",
  "What’s something you do that builds trust with others?",
  "What kind of support do you find easiest to give?",
  "What helps you be fully present with someone?",
  "What’s a type of vulnerability you find hardest?",
  "What do you love most about your chosen community?",
  "What helps you share parts of yourself that feel hidden?",
  "What’s a compliment you gave recently that felt really true?",
  "What’s something you’ve realized about yourself through connection?",
  "What’s something you hope to create in every relationship?",
  "What’s something you used to fear about connection that you now enjoy?",
  "How do you hold emotional space for someone who needs it?",
  "What kind of memories do you love collecting with people?",
  "What does “emotional generosity” mean to you?",
  "What’s a relationship where you felt truly empowered?",
  "What’s something you admire in people who love fearlessly?",
  "What helps you come back to yourself after conflict?",
  "What’s your favorite way to connect in a group setting?",
  "What’s something about you that makes people feel comfortable?",
  "How do you stay emotionally open after being hurt?",
  "What’s a relationship milestone that meant a lot to you?",
  "What does reciprocity mean to you in a friendship?",
  "What do you do when you want to deepen a bond?",
  "What’s a time when you really felt chosen?",
  "What’s something that reminds you how much you’ve grown?",
  "What helps you communicate your needs clearly?",
  "How do you celebrate emotional wins with friends?",
  "What’s your favorite thing about being deeply known by someone?",
  "What’s something that always brings you closer to others?",
  "How do you remind people they’re not alone?",
  "What’s your emotional superpower in relationships?",
  "What’s something people feel safe telling you?",
  "How do you build emotional closeness over time?",
  "What’s a word you’d use to describe your ideal friendship?",
  "What makes you feel confident in your ability to love well?",
  "What do you bring into relationships that others value?",
  "What’s something small you’ve done that made a big difference for someone?",
  "How do you show grace when people make mistakes?",
  "What’s something you love about human connection in general?",
  "What’s a truth you’ve discovered through building meaningful relationships?",
  "What’s a place you’ve always wanted to visit, and why?"
];